// Monster Level 0: factor 70368744177664 (factor)
// Monster Level 7: factor 19 (factor)
// Monster Level 14: factor 71 (SENTINEL)
// Monster Level 21: factor 71 (SENTINEL)
// Monster Level 28: factor 71 (SENTINEL)
// Monster Level 35: factor 71 (SENTINEL)
// Monster Level 42: factor 71 (SENTINEL)
// Monster Level 49: factor 71 (SENTINEL)
// Monster Level 56: factor 71 (SENTINEL)
// Monster Level 63: factor 71 (SENTINEL)
// Monster Level 70: factor 71 (SENTINEL)
// Monster Level 77: factor 71 (SENTINEL)
// Monster Level 84: factor 71 (SENTINEL)
// Monster Level 91: factor 71 (SENTINEL)
// Monster Level 98: factor 71 (SENTINEL)
// Monster Level 105: factor 71 (SENTINEL)

// Generated by Monster Group Symbiotic Compiler
#[no_mangle]
pub extern "C" fn monster_main() -> i32 {
    let x = 42; // Processed by ant workers
    if x > 0 {  // Elevated through fungus gardens
        71      // Monster Group sentinel value
    } else {
        0
    }
}
