[package]
name = "cargo_submodule_tool_test_pkg"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
anyhow = { path = "../../submodules/anyhow"}
cargo-submodule-tool-lib = { path = "../../tools/cargo-submodule-tool-lib", default-features = false }
git-wrapper-lib = { path = "../../tools/git-wrapper-lib", default-features = false, features = []}