[package]
name = "cargo-edit-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-submodule-tool-lib = { path = "../cargo-submodule-tool-lib", optional = true }
syn = { version = "*", optional = true }
clap = { version = "*", optional = true }

git2 = { version = "*", optional = true }
hex = { version = "*", optional = true }
sha1 = { version = "*", optional = true }
pathdiff = { version = "*", optional = true }
git-wrapper-lib = { path = "../git-wrapper-lib", optional = true }
anyhow = { workspace = true, optional = true }
cargo_metadata = { workspace = true, optional = true } # Made optional
serde = { workspace = true, optional = true } # Made optional
serde_json = { workspace = true, optional = true } # Made optional
#git-wrapper-lib = { path = "../git-wrapper-lib", optional = true }
regex = { workspace = true, optional = true }
lazy_static = { workspace = true, optional = true }
toml_edit = { workspace = true, optional = true }
walkdir = { workspace = true, optional = true }

[features]

syn_enabled = ["dep:syn"]
clap_enabled = ["dep:clap"]

git2_enabled = ["dep:git2"]
hex_enabled = ["dep:hex"]
cargo_metadata_enabled = ["dep:cargo_metadata"]
sha1_enabled = ["dep:sha1"]
pathdiff_enabled = ["dep:pathdiff"]
default = [] # No default features
serde_enabled = ["dep:serde"]
serde_json_enabled = ["dep:serde_json"]
real_cargo_metadata = ["dep:cargo_metadata"] # Feature to enable real cargo_metadata
regex_enabled = ["dep:regex"]
lazy_static_enabled = ["dep:lazy_static"]
toml_edit_enabled = ["dep:toml_edit"]
walkdir_enabled = ["dep:walkdir"]
anyhow_enabled = ["dep:anyhow"]
git_wrapper_lib_enabled = ["dep:git-wrapper-lib"]