# This file was @generated by cargo2nix.
# It is not intended to be manually edited.

{ rustLib, lib, ... }:

let
  mkRustCrate = { ... }: { }; # Dummy mkRustCrate
in
{
  cargo2nixVersion = "0.12.0";
  workspace = {
    cargo2nix = {
      name = "cargo2nix";
      version = "0.12.0";
      src = null; # Dummy source
      dependencies = { };
    };
  };
  unknown.cargo2nix."0.12.0" = {
    name = "cargo2nix";
    version = "0.12.0";
    src = null; # Dummy source
    dependencies = { };
  };
}
