[workspace.package]
categories = []
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
rust-version = "1.89"
edition = "2024"
#resolver = "3"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/meta-introspector/cargo2nix"
repository = "https://github.com/meta-introspector/cargo2nix"
keywords = ["rust"]
include = [
  "build.rs",
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[workspace]
resolver = "3"
members = [
    "crates/factory_block_factory_block",
    "crates/monster_math_traits",
    "crates/rusttycoon",
    "crates/factory_abi",
    "crates/solana-monster-system",
    "crates/ast_parser_impl",
]
exclude = [
    "crates/solana-monster-system/generated_pure_traits.rs",
]

[workspace.lints.rust]
incomplete_features = "allow"
rust_2018_idioms = "allow" # TODO: could this be removed?
unexpected_cfgs = { level = "allow" }
unused_qualifications = "allow"
warnings = "allow"

[workspace.lints.rustdoc]
private_intra_doc_links = "allow"

[workspace.lints.clippy]
all = { level = "allow", priority = -2 }
correctness = { level = "allow", priority = -1 }
dbg_macro = "allow"
disallowed_methods = "allow"
print_stderr = "allow"
print_stdout = "allow"
self_named_module_files = "allow"
explicit_iter_loop = "allow"
identity_op = "allow"
manual_assert = "allow"
map_unwrap_or = "allow"
missing_safety_doc = "allow"
non_minimal_cfg = "allow"
ptr_as_ptr = "allow"
unnecessary_semicolon = "allow"
expl_impl_clone_on_copy = "allow"
uninlined_format_args = "allow"
unnecessary_cast = "allow"
used_underscore_binding = "allow"

[workspace.dependencies]
aho-corasick= "1.1.4"
anyhow= "1.0.100"
async-graphql = "7.0"
rocksdb = "0.21.0" # Added rocksdb dependency to workspace
block-buffer= "0.10.4"
camino= "1.2.1"
cargo-platform= "0.3.1"
cargo="0.92.0" # 94
cargo_metadata= "0.23.1"
cfg-if= "1.0.4"
clap = "4.5.53"
clap_complete="4.5.61"
clap_derive="4.5.49"
colorify="0.2.3"
cpufeatures= "0.2.17"
crypto-common= "0.1.6"
digest= "0.10.7"
equivalent= "1.0.2"
fs_extra="1.3.0"
generic-array= "0.14.9"
git2="0.20.2"
hashbrown= "0.16.1"
hex= "0.4.3"
indexmap= "2.12.1"
itoa= "1.0.15"
lazy_static="1.5.0"
libc= "0.2.177"
md5="0.8.0"
memchr= "2.7.6"
pathdiff= "0.2.3"
proc-macro2 = { path = "submodules/proc-macro2" }
quote= "1.0.42"
regex-automata= "0.4.13"
regex-syntax= "0.8.8"
regex= "1.12.2"
ryu= "1.0.20"
same-file= "1.0.6"
semver= "1.0.27"
serde= "1.0.228"
serde_core= "1.0.228"
serde_derive= "1.0.228"
serde_json= "1.0.145"
sha1= "0.10.6"
sha2="0.10.9"
syn= "2.0.110"
tempfile="3.23.0"
tera="1.20.1"
thiserror-impl= "2.0.17"
thiserror= "2.0.17"
tokio = { version = "1.0", features = ["full"] }
toml="0.9.8"
toml_datetime= "0.7.3"
toml_edit= "0.23.7"
toml_parser= "1.0.4"
toml_writer= "1.0.4"
typenum= "1.19.0"
unicode-ident= "1.0.22"
url="2.5.7"
version_check= "0.9.5"
walkdir = { path = "submodules/walkdir" }
cargo-repo-sync-lib = { path = "./tools/cargo-repo-sync-lib" }
git-wrapper-lib = { path = "./tools/git-wrapper-lib" }
cargo-submodule-tool-lib = { path = "./tools/cargo-submodule-tool-lib" }
tool-traits-lib = { path = "./tools/tool-traits-lib" }



