#!/usr/bin/env bash

# This script reads a JSON plan generated by the repo_manager Rust program
# and executes the corresponding Git and GitHub CLI commands.
#
# Usage: ./execute_gh_plan.sh [--dry-run]
#
# Dependencies:
# - jq: A lightweight and flexible command-line JSON processor.
# - gh: GitHub CLI.
# - git: Git version control system.

DRY_RUN=false

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        --dry-run)
            DRY_RUN=true
            ;;
        *)
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
    shift
done

if [ "$DRY_RUN" = true ]; then
    echo "--- DRY RUN MODE ACTIVE (Shell Script) ---"
    echo "Commands will be printed but NOT executed."
fi

# --- Configuration (ensure these paths are correct for your Nix environment) ---
# These should ideally be sourced from your Nix profile or environment.
# For now, we'll assume they are in the PATH or use common Nix paths.
GIT_BIN="/data/data/com.termux.nix/files/home/.nix-profile/bin/git"
GH_BIN="/data/data/com.termux.nix/files/home/.nix-profile/bin/gh"

# Check for dependencies
command -v jq >/dev/null 2>&1 || { echo >&2 "Error: 'jq' is not installed. Please install it to run this script."; exit 1; }
[ -x "$GIT_BIN" ] || { echo >&2 "Error: Git executable not found or not executable at $GIT_BIN. Please check your Nix environment."; exit 1; }
[ -x "$GH_BIN" ] || { echo >&2 "Error: GitHub CLI executable not found or not executable at $GH_BIN. Please check your Nix environment."; exit 1; }

# Run the Rust program to generate the JSON plan
echo "Generating action plan using repo_manager Rust program..."
TEMP_JSON_FILE=$(mktemp)
if ! cargo run --package repo_manager -- --root-dir . --output-file "$TEMP_JSON_FILE" 2>/dev/null; then
    echo "Error: repo_manager Rust program failed to generate plan."
    # For debugging, you might want to remove 2>/dev/null from the above line
    rm "$TEMP_JSON_FILE" # Clean up temp file on error
    exit 1
fi

# Parse the JSON plan
echo "Parsing JSON plan from $TEMP_JSON_FILE..."

# Read each action from the JSON plan
jq -c '.[]' "$TEMP_JSON_FILE" | while read -r i; do
    REPO_URL=$(echo "$i" | jq -r '.repo_url')
    OWNER=$(echo "$i" | jq -r '.owner')
    REPO_NAME=$(echo "$i" | jq -r '.repo_name')
    SUBMODULE_PATH=$(echo "$i" | jq -r '.submodule_path')
    TARGET_ORG=$(echo "$i" | jq -r '.target_org')
    TARGET_BRANCH=$(echo "$i" | jq -r '.target_branch')

    echo "--- Processing ${REPO_URL} ---"

    # 1. Clone repository
    if [ ! -d "$SUBMODULE_PATH" ]; then
        CLONE_CMD="$GIT_BIN clone \"$REPO_URL\" \"$SUBMODULE_PATH\""
        if [ "$DRY_RUN" = true ]; then
            echo "[DRY RUN] $CLONE_CMD"
        else
            echo "Executing: $CLONE_CMD"
            eval "$CLONE_CMD" || { echo "Error: Failed to clone $REPO_URL"; continue; }
        fi
    else
        echo "Submodule directory $SUBMODULE_PATH already exists. Skipping clone."
    fi

    # Change into the submodule directory for subsequent git operations
    if [ "$DRY_RUN" = false ]; then
        if [ ! -d "$SUBMODULE_PATH" ]; then
            echo "Error: Submodule directory $SUBMODULE_PATH does not exist after clone attempt. Skipping further operations for this repo."
            continue
        fi
        pushd "$SUBMODULE_PATH" >/dev/null || { echo "Error: Failed to change directory to $SUBMODULE_PATH"; continue; }
    fi

    # 2. Manage remotes (rename origin to upstream, add new origin)
    # Check if 'origin' remote exists
    if [ "$DRY_RUN" = true ]; then
        echo "[DRY RUN] $GIT_BIN -C \"$SUBMODULE_PATH\" remote get-url origin"
    else
        if "$GIT_BIN" -C "$SUBMODULE_PATH" remote get-url origin >/dev/null 2>&1; then # origin exists
            # Check if 'upstream' remote exists
            if ! "$GIT_BIN" -C "$SUBMODULE_PATH" remote get-url upstream >/dev/null 2>&1; then # upstream does not exist
                RENAME_CMD="$GIT_BIN -C \"$SUBMODULE_PATH\" remote rename origin upstream"
                if [ "$DRY_RUN" = true ]; then
                    echo "[DRY RUN] $RENAME_CMD"
                else
                    echo "Executing: $RENAME_CMD"
                    eval "$RENAME_CMD" || { echo "Error: Failed to rename origin to upstream in $SUBMODULE_PATH"; popd >/dev/null || continue; continue; }
                fi
            else
                echo "Remote 'upstream' already exists in $SUBMODULE_PATH. Skipping renaming 'origin'."
            fi
        fi
    fi

    NEW_ORIGIN_URL="https://github.com/${TARGET_ORG}/${REPO_NAME}.git"
    if [ "$DRY_RUN" = true ]; then
        echo "[DRY RUN] $GIT_BIN -C \"$SUBMODULE_PATH\" remote get-url origin"
    else
        if ! "$GIT_BIN" -C "$SUBMODULE_PATH" remote get-url origin >/dev/null 2>&1; then # origin does not exist (or was renamed)
            ADD_ORIGIN_CMD="$GIT_BIN -C \"$SUBMODULE_PATH\" remote add origin \"$NEW_ORIGIN_URL\""
            if [ "$DRY_RUN" = true ]; then
                echo "[DRY RUN] $ADD_ORIGIN_CMD"
            else
                echo "Executing: $ADD_ORIGIN_CMD"
                eval "$ADD_ORIGIN_CMD" || { echo "Error: Failed to add new origin in $SUBMODULE_PATH"; popd >/dev/null || continue; continue; }
            fi
        else
            echo "Remote 'origin' already exists in $SUBMODULE_PATH. Skipping adding new origin."
        fi
    fi

    # 3. Fork repository using gh CLI
    FORK_CMD="$GH_BIN repo fork \"${OWNER}/${REPO_NAME}\" --org \"${TARGET_ORG}\" --remote --fork-name \"${REPO_NAME}\""
    if [ "$DRY_RUN" = true ]; then
        echo "[DRY RUN] $FORK_CMD"
    else
        echo "Skipping execution of: $FORK_CMD (manual review and execution required)"
        # eval "$FORK_CMD" || echo "Warning: Failed to fork ${OWNER}/${REPO_NAME}. It might already be forked or 'gh' CLI is not configured. Continuing..."
    fi

    # 4. Checkout target branch
    CHECKOUT_CMD="$GIT_BIN -C \"$SUBMODULE_PATH\" checkout \"$TARGET_BRANCH\""
    if [ "$DRY_RUN" = true ]; then
        echo "[DRY RUN] $CHECKOUT_CMD"
    else
        echo "Executing: $CHECKOUT_CMD"
        eval "$CHECKOUT_CMD" || { # Branch might not exist, try creating it
            CREATE_BRANCH_CMD="$GIT_BIN -C \"$SUBMODULE_PATH\" checkout -b \"$TARGET_BRANCH\""
            if [ "$DRY_RUN" = true ]; then
                echo "[DRY RUN] $CREATE_BRANCH_CMD"
            else
                echo "Executing: $CREATE_BRANCH_CMD"
                eval "$CREATE_BRANCH_CMD" || { echo "Error: Failed to checkout or create branch $TARGET_BRANCH in $SUBMODULE_PATH"; popd >/dev/null || continue; continue; }
            fi
        }
    fi

    if [ "$DRY_RUN" = false ]; then
        popd >/dev/null || { echo "Error: Failed to popd from $SUBMODULE_PATH"; continue; }
    fi

    echo "--- Finished processing ${REPO_URL} ---"
    echo
done

# Clean up temporary JSON file
rm "$TEMP_JSON_FILE"

echo "All repositories processed (plan generated by Rust, executed by shell script)."
