{
  description = "Nix flake for Oracle OCI with sops-managed SSH key";

  inputs = {
    nixpkgs.url = "github:meta-introspector/nixpkgs?ref=feature/CRQ-016-nixify";
    flake-utils.url = "github:meta-introspector/flake-utils?ref=feature/CRQ-016-nixify";
    sops-nix.url = "github:Mic92/sops-nix"; # Adding sops-nix input
  };

  outputs = { self, nixpkgs, flake-utils, sops-nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config = {
            permittedInsecurePackages = [ "openssl-1.1.1w" ];
          };
        };

        # Generate a new SSH key pair
        generatedSshKey = pkgs.runCommand "oci-ssh-key"
          {
            nativeBuildInputs = [ pkgs.openssh ];
          } ''
          mkdir -p $out
          ssh-keygen -t ed25519 -f $out/id_ed25519 -N ""
        '';

        # Generate a new GPG key and extract its fingerprint
        generatedGpgKey = pkgs.runCommand "oci-gpg-key"
          {
            nativeBuildInputs = [ pkgs.gnupg ];
            # Define a deterministic GPG key generation script
            gpgBatchConfig = pkgs.writeText "gpg-batch-config" ''
              %echo Generating a GPG key
              Key-Type: EDDSA
              Key-Curve: ed25519
              Subkey-Type: ECDH
              Subkey-Curve: cv25519
              Name-Real: OCI Nix Flake
              Name-Comment: Generated by Nix flake for OCI access
              Name-Email: oci-nix-flake@example.com
              Expire-Date: 0
              Passphrase: ""
              %commit
              %echo Done
            '';
          } ''
          export GNUPGHOME=$(mktemp -d)
          chmod 700 $GNUPGHOME

          # Generate the GPG key
          gpg --batch --full-generate-key --expert --pinentry-mode loopback --passphrase "" --no-tty --batch --gen-batch $gpgBatchConfig

          # Export the public key
          gpg --export --armor "OCI Nix Flake" > $out/oci-gpg-public.asc

          # Export the secret key (for sops to use)
          gpg --export-secret-keys --armor "OCI Nix Flake" > $out/oci-gpg-secret.asc

          # Extract the fingerprint
          echo "GPG_FINGERPRINT=$(gpg --list-secret-keys --with-colons "OCI Nix Flake" | grep "fpr" | head -n 1 | cut -d: -f10)" > $out/fingerprint
        '';

        # Extract the fingerprint from the generatedGpgKey output
        gpgFingerprint = (pkgs.lib.strings.fileContents "${generatedGpgKey}/fingerprint");

        # Configure sops-nix
        sops = sops-nix.lib.${system}.sops {
          sopsDir = ./oci/secrets; # Directory containing encrypted secrets
          sopsFile = ./oci/sops.yaml; # sops configuration file
          gnupg.keyring = [ "${generatedGpgKey}/oci-gpg-public.asc" ]; # Use the generated GPG public key
          gnupg.secretKeyring = [ "${generatedGpgKey}/oci-gpg-secret.asc" ]; # Use the generated GPG secret key
        };

        # Define the OCI deployment/connection
        ociDeployment = pkgs.writeShellScriptBin "oci-connect" ''
          # Ensure the decrypted key has correct permissions
          chmod 0600 ${sops.placeholder."oci-ssh-key.age"}

          # Connect to the OCI instance
          ssh -i ${sops.placeholder."oci-ssh-key.age"} ubuntu@129.213.85.94 "$@"
        '';

      in
      rec {
        devShells = {
          default = pkgs.mkShell {
            packages = [
              pkgs.openssh
              pkgs.sops
              pkgs.gnupg # Add gnupg to the devShell
              ociDeployment
            ];
            shellHook = ''
              echo "To connect to OCI, run: oci-connect"
              echo "Generated SSH private key: ${generatedSshKey}/id_ed25519"
              echo "Generated SSH public key: ${generatedSshKey}/id_ed25519.pub"
              echo "Generated GPG public key: ${generatedGpgKey}/oci-gpg-public.asc"
              echo "Generated GPG secret key: ${generatedGpgKey}/oci-gpg-secret.asc"
              echo "GPG Fingerprint for sops: $(cat ${generatedGpgKey}/fingerprint)"
              echo "Please update oci/sops.yaml with this fingerprint."
              echo "Then, encrypt your SSH private key using 'sops encrypt oci/secrets/oci-ssh-key.age --encrypted-regex '^(data|string)$'' "
            '';
          };
        };

        packages = rec {
          default = ociDeployment;
          ociSshKey = generatedSshKey;
          ociGpgKey = generatedGpgKey;
        };

        apps = rec {
          ociConnect = { type = "
              app "; program = "${ociDeployment}/bin/oci-connect"; };
          default = ociConnect;
        };
      }
    );
}

