#!/bin/bash

# Target directory for ls, defaults to current directory
TARGE T_DIR="${1:-.}"

# Get the list of directory entries, quoted and with non-printable characters escaped
LS_OUTPUT=$(ls -b "$TARGET_DIR")

# Start building the Rust file content
RUST_FILE_FILE="submodules/rust/compiler/lib-macro-rule/src/generated_test.rs"

# Initialize RUST_FILE_CONTENT
RUST_FILE_CONTENT=""
RUST_FILE_CONTENT+="//! Generated by lib.sh\n\n"
RUST_FILE_CONTENT+="use std::collections::hash_map::DefaultHasher;\n"
RUST_FILE_CONTENT+="use std::hash::{Hash, Hasher};\n\n"

RUST_FILE_CONTENT+="macro_rules! SOMEMACRO {\n"
RUST_FILE_CONTENT+="    (\* ( \\$dir:literal ),* ) => {\n"
RUST_FILE_CONTENT+="        // Placeholder for ZKP integration later\n"
RUST_FILE_CONTENT+="        // println!(\"ZKP proof for directory listing: [placeholder]\");\n"
RUST_FILE_CONTENT+="        println!(\"Processing directories:\");\n"
RUST_FILE_CONTENT+="        \$\( \n"
RUST_FILE_CONTENT+="            println!(\"- {}\", \$dir);\n"
RUST_FILE_CONTENT+="        )*\n"
RUST_FILE_CONTENT+="    };\n"
RUST_FILE_CONTENT+="}\n\n"

RUST_FILE_CONTENT+="fn calculate_hash<T: Hash>(t: &T) -> u64 {\n"
RUST_FILE_CONTENT+="    let mut s = DefaultHasher::new();\n"
RUST_FILE_CONTENT+="    t.hash(&mut s);\n"
RUST_FILE_CONTENT+="    s.finish()\n"
RUST_FILE_CONTENT+="}\n\n"

RUST_FILE_CONTENT+="fn main() {\n"

# Add macro call with ls output
RUST_FILE_CONTENT+="    SOMEMACRO!(\n"
FIRST=true
while IFS= read -r LINE; do
    if [ "$FIRST" = true ]; then
        RUST_FILE_CONTENT+="        \"$LINE\""
        FIRST=false
    else
        RUST_FILE_CONTENT+", \"$LINE\""
    fi
done <<< "$LS_OUTPUT"
RUST_FILE_CONTENT+="    \n    );

"

# Add state hash placeholder
HASH_OF_LS_OUTPUT=$(echo "$LS_OUTPUT" | sha256sum | awk '{print $1}')
RUST_FILE_CONTENT+="    // Placeholder for state hash of ls output\n"
RUST_FILE_CONTENT+="    let ls_output_hash = \"$HASH_OF_LS_OUTPUT\";\n"
RUST_FILE_CONTENT+="    println!(\"State hash of ls output: {}$", ls_output_hash);\n"
RUST_FILE_CONTENT+="}\n"

# Write to the Rust file
echo -e "$RUST_FILE_CONTENT" > "$RUST_FILE_FILE"

echo "Generated $RUST_FILE_FILE"