#!/bin/bash

git submodule add https://github.com/cc-rs/cc-rs.git submodules/cc-rs
git submodule add https://github.com/meta-introspector/cc-rs.git submodules/cc-rs-meta
git submodule add https://github.com/rustfmt/rustfmt.git submodules/rustfmt
git submodule add https://github.com/meta-introspector/rustfmt.git submodules/rustfmt-meta
git submodule add https://github.com/rust-lang/rust.git submodules/rust
git submodule add https://github.com/meta-introspector/rust.git submodules/rust-meta
git submodule add https://github.com/rust-lang/rust-clippy.git submodules/rust-clippy
git submodule add https://github.com/meta-introspector/rust-clippy.git submodules/rust-clippy-meta
git submodule add https://github.com/rust-lang/cargo.git submodules/cargo
git submodule add https://github.com/meta-introspector/cargo.git submodules/cargo-meta
git submodule add https://github.com/cargo2nix/cargo2nix.git submodules/cargo2nix
git submodule add https://github.com/meta-introspector/cargo2nix.git submodules/cargo2nix-meta
git submodule add https://github.com/cmake-rs/cmake-rs.git submodules/cmake-rs
git submodule add https://github.com/meta-introspector/cmake-rs.git submodules/cmake-rs-meta
git submodule add https://github.com/toml/toml.git submodules/toml
git submodule add https://github.com/meta-introspector/toml.git submodules/toml-meta
git submodule add https://github.com/crypto-bigint/crypto-bigint.git submodules/crypto-bigint
git submodule add https://github.com/meta-introspector/crypto-bigint.git submodules/crypto-bigint-meta
git submodule add https://github.com/serde-rs/serde.git submodules/serde
git submodule add https://github.com/meta-introspector/serde.git submodules/serde-meta
git submodule add https://github.com/h2/h2.git submodules/h2
git submodule add https://github.com/meta-introspector/h2.git submodules/h2-meta
git submodule add https://github.com/rustls-native-certs/rustls-native-certs.git submodules/rustls-native-certs
git submodule add https://github.com/meta-introspector/rustls-native-certs.git submodules/rustls-native-certs-meta
git submodule add https://github.com/foldhash/foldhash.git submodules/foldhash
git submodule add https://github.com/meta-introspector/foldhash.git submodules/foldhash-meta
git submodule add https://github.com/fiat-crypto/fiat-crypto.git submodules/fiat-crypto
git submodule add https://github.com/meta-introspector/fiat-crypto.git submodules/fiat-crypto-meta
git submodule add https://github.com/bincode/bincode.git submodules/bincode
git submodule add https://github.com/meta-introspector/bincode.git submodules/bincode-meta
git submodule add https://github.com/scoped-tls/scoped-tls.git submodules/scoped-tls
git submodule add https://github.com/meta-introspector/scoped-tls.git submodules/scoped-tls-meta
git submodule add https://github.com/hyper-rustls/hyper-rustls.git submodules/hyper-rustls
git submodule add https://github.com/meta-introspector/hyper-rustls.git submodules/hyper-rustls-meta
git submodule add https://github.com/fxhash/fxhash.git submodules/fxhash
git submodule add https://github.com/meta-introspector/fxhash.git submodules/fxhash-meta
git submodule add https://github.com/warp/warp.git submodules/warp
git submodule add https://github.com/meta-introspector/warp.git submodules/warp-meta
git submodule add https://github.com/reqwest/reqwest.git submodules/reqwest
git submodule add https://github.com/meta-introspector/reqwest.git submodules/reqwest-meta
git submodule add https://github.com/async-std/async-std.git submodules/async-std
git submodule add https://github.com/meta-introspector/async-std.git submodules/async-std-meta
git submodule add https://github.com/ring/ring.git submodules/ring
git submodule add https://github.com/meta-introspector/ring.git submodules/ring-meta
git submodule add https://github.com/hashbrown/hashbrown.git submodules/hashbrown
git submodule add https://github.com/meta-introspector/hashbrown.git submodules/hashbrown-meta
git submodule add https://github.com/futures-rs/futures-rs.git submodules/futures-rs
git submodule add https://github.com/meta-introspector/futures-rs.git submodules/futures-rs-meta
git submodule add https://github.com/cryptocorrosion/cryptocorrosion.git submodules/cryptocorrosion
git submodule add https://github.com/meta-introspector/cryptocorrosion.git submodules/cryptocorrosion-meta
git submodule add https://github.com/hyper-tls/hyper-tls.git submodules/hyper-tls
git submodule add https://github.com/meta-introspector/hyper-tls.git submodules/hyper-tls-meta
git submodule add https://github.com/crossbeam/crossbeam.git submodules/crossbeam
git submodule add https://github.com/meta-introspector/crossbeam.git submodules/crossbeam-meta
git submodule add https://github.com/hash32/hash32.git submodules/hash32
git submodule add https://github.com/meta-introspector/hash32.git submodules/hash32-meta
git submodule add https://github.com/tls/tls.git submodules/tls
git submodule add https://github.com/meta-introspector/tls.git submodules/tls-meta
git submodule add https://github.com/ahash/ahash.git submodules/ahash
git submodule add https://github.com/meta-introspector/ahash.git submodules/ahash-meta
git submodule add https://github.com/twox-hash/twox-hash.git submodules/twox-hash
git submodule add https://github.com/meta-introspector/twox-hash.git submodules/twox-hash-meta
git submodule add https://github.com/rustc-stable-hash/rustc-stable-hash.git submodules/rustc-stable-hash
git submodule add https://github.com/meta-introspector/rustc-stable-hash.git submodules/rustc-stable-hash-meta
git submodule add https://github.com/rustls/rustls.git submodules/rustls
git submodule add https://github.com/meta-introspector/rustls.git submodules/rustls-meta
git submodule add https://github.com/tokio-rustls/tokio-rustls.git submodules/tokio-rustls
git submodule add https://github.com/meta-introspector/tokio-rustls.git submodules/tokio-rustls-meta
git submodule add https://github.com/rustls-ffi/rustls-ffi.git submodules/rustls-ffi
git submodule add https://github.com/meta-introspector/rustls-ffi.git submodules/rustls-ffi-meta
git submodule add https://github.com/yaml-rust2/yaml-rust2.git submodules/yaml-rust2
git submodule add https://github.com/meta-introspector/yaml-rust2.git submodules/yaml-rust2-meta
git submodule add https://github.com/hyperium/hyper.git submodules/hyper
git submodule add https://github.com/meta-introspector/hyper.git submodules/hyper-meta
git submodule add https://github.com/rustls-platform-verifier/rustls-platform-verifier.git submodules/rustls-platform-verifier
git submodule add https://github.com/meta-introspector/rustls-platform-verifier.git submodules/rustls-platform-verifier-meta
git submodule add https://github.com/http/http.git submodules/http
git submodule add https://github.com/meta-introspector/http.git submodules/http-meta
git submodule add https://github.com/rustc-hash/rustc-hash.git submodules/rustc-hash
git submodule add https://github.com/meta-introspector/rustc-hash.git submodules/rustc-hash-meta
git submodule add https://github.com/tokio-rs/tokio.git submodules/tokio
git submodule add https://github.com/meta-introspector/tokio.git submodules/tokio-meta
git submodule add https://github.com/rayon/rayon.git submodules/rayon
git submodule add https://github.com/meta-introspector/rayon.git submodules/rayon-meta
git submodule add https://github.com/hashes/hashes.git submodules/hashes
git submodule add https://github.com/meta-introspector/hashes.git submodules/hashes-meta
git submodule add https://github.com/json/json.git submodules/json
git submodule add https://github.com/meta-introspector/json.git submodules/json-meta
git submodule add https://github.com/hashlink/hashlink.git submodules/hashlink
git submodule add https://github.com/meta-introspector/hashlink.git submodules/hashlink-meta
