git submodule add https://github.com/meta-introspector/is_terminal_polyfill submodules/submodules/is_terminal_polyfill
git submodule add https://github.com/meta-introspector/similar.git submodules/submodules/similar
git submodule add https://github.com/meta-introspector/tracing submodules/submodules/tracing
git submodule add https://github.com/meta-introspector/proc-macro-crate submodules/submodules/proc-macro-crate
git submodule add https://github.com/meta-introspector/nom.git submodules/submodules/nom
git submodule add https://github.com/meta-introspector/option_set.git submodules/submodules/option_set
git submodule add https://github.com/meta-introspector/open-rs.git submodules/submodules/open-rs
git submodule add https://github.com/meta-introspector/derive-ex submodules/submodules/derive-ex
git submodule add https://github.com/meta-introspector/rust-fallible-iterator submodules/submodules/rust-fallible-iterator
git submodule add https://github.com/meta-introspector/rust-ordered-float submodules/submodules/rust-ordered-float
git submodule add https://github.com/meta-introspector/unicase submodules/submodules/unicase
git submodule add https://gitlab.redox-os.org/redox-os/libredox.git submodules/submodules/libredox
git submodule add https://github.com/anza-xyz/rustc-build-sysroot submodules/submodules/rustc-build-sysroot
git submodule add https://github.com/meta-introspector/tokio submodules/submodules/tokio
git submodule add https://github.com/smol-rs/async-signal submodules/submodules/async-signal
git submodule add https://github.com/meta-introspector/vte.git submodules/submodules/vte
git submodule add https://github.com/meta-introspector/openssl-probe.git submodules/submodules/openssl-probe
git submodule add https://github.com/meta-introspector/tinyvec_macros submodules/submodules/tinyvec_macros
git submodule add https://github.com/meta-introspector/nix.git submodules/submodules/nix
git submodule add https://github.com/meta-introspector/yaml-rust2.git submodules/submodules/yaml-rust2
git submodule add https://github.com/meta-introspector/scoped-tls.git submodules/submodules/scoped-tls
git submodule add https://github.com/meta-introspector/formats submodules/submodules/formats
git submodule add https://github.com/smol-rs/async-fs submodules/submodules/async-fs
git submodule add https://github.com/meta-introspector/pathdiff.git submodules/submodules/pathdiff
git submodule add https://github.com/meta-introspector/zlib-rs submodules/submodules/zlib-rs
git submodule add https://github.com/meta-introspector/event-listener submodules/submodules/event-listener
git submodule add https://github.com/meta-introspector/hermit-rs.git submodules/submodules/hermit-rs
git submodule add https://github.com/meta-introspector/trycmd.git submodules/submodules/trycmd
git submodule add https://github.com/meta-introspector/serde-value.git submodules/submodules/serde-value
git submodule add https://github.com/meta-introspector/supports-unicode submodules/submodules/supports-unicode
git submodule add https://github.com/meta-introspector/rusty-fork.git submodules/submodules/rusty-fork
git submodule add https://github.com/meta-introspector/async-global-executor.git submodules/submodules/async-global-executor
git submodule add https://github.com/meta-introspector/event-listener-strategy submodules/submodules/event-listener-strategy
git submodule add https://github.com/meta-introspector/strsim-rs.git submodules/submodules/strsim-rs
git submodule add https://github.com/meta-introspector/eyre submodules/submodules/eyre
git submodule add https://github.com/meta-introspector/eigenvalues submodules/tools/eigenvalues
git submodule add https://github.com/meta-introspector/rust-csv.git submodules/submodules/rust-csv
git submodule add https://github.com/meta-introspector/rust-security-framework.git submodules/submodules/rust-security-framework
git submodule add https://github.com/meta-introspector/byteorder.git submodules/submodules/byteorder
git submodule add https://github.com/meta-introspector/async-task submodules/submodules/async-task
git submodule add https://github.com/meta-introspector/tui-crates.git submodules/submodules/tui-crates
git submodule add https://github.com/meta-introspector/iana-time-zone submodules/submodules/iana-time-zone
git submodule add https://github.com/meta-introspector/ptyprocess submodules/submodules/ptyprocess
git submodule add https://github.com/meta-introspector/pest submodules/submodules/pest
git submodule add https://github.com/meta-introspector/config-rs submodules/submodules/config-rs
git submodule add https://github.com/meta-introspector/pin-project-lite submodules/submodules/pin-project-lite
git submodule add https://github.com/meta-introspector/html-escape.git submodules/submodules/html-escape
git submodule add https://github.com/meta-introspector/r-efi submodules/submodules/r-efi
git submodule add https://github.com/meta-introspector/hashlink.git submodules/submodules/hashlink
git submodule add https://github.com/meta-introspector/snapbox.git submodules/submodules/snapbox
git submodule add https://github.com/meta-introspector/winreg-rs.git submodules/submodules/winreg-rs
git submodule add https://github.com/meta-introspector/arc-swap submodules/submodules/arc-swap
git submodule add https://github.com/meta-introspector/rstest.git submodules/submodules/rstest
git submodule add https://github.com/meta-introspector/corn.git submodules/submodules/corn
git submodule add https://github.com/meta-introspector/human-format-rs.git submodules/submodules/human-format-rs
git submodule add https://github.com/meta-introspector/utf8-width.git submodules/submodules/utf8-width
git submodule add https://github.com/meta-introspector/proc-macro2.git submodules/submodules/proc-macro2
git submodule add https://github.com/rustwasm/gloo submodules/submodules/gloo
git submodule add https://github.com/meta-introspector/ratatui submodules/submodules/ratatui
git submodule add https://github.com/meta-introspector/log submodules/submodules/log
git submodule add https://github.com/meta-introspector/arbitrary submodules/submodules/arbitrary
git submodule add https://github.com/meta-introspector/hyper-util.git submodules/submodules/hyper-util
git submodule add https://github.com/meta-introspector/vec_mut_scan.git submodules/submodules/vec_mut_scan
git submodule add https://github.com/meta-introspector/is-wsl submodules/submodules/is-wsl
git submodule add https://github.com/meta-introspector/slab submodules/submodules/slab
git submodule add https://github.com/meta-introspector/httpdate submodules/submodules/httpdate
git submodule add https://github.com/meta-introspector/varisat.git submodules/submodules/varisat
git submodule add https://github.com/meta-introspector/assert_matches.git submodules/submodules/assert_matches
git submodule add https://github.com/TedDriggs/ident_case submodules/submodules/ident_case
git submodule add https://github.com/meta-introspector/hyper-tls.git submodules/submodules/hyper-tls
git submodule add https://github.com/meta-introspector/rustix.git submodules/submodules/rustix
git submodule add https://github.com/meta-introspector/cc-rs submodules/submodules/cc-rs
git submodule add https://github.com/meta-introspector/darling submodules/submodules/darling
git submodule add https://github.com/meta-introspector/tar-rs.git submodules/submodules/tar-rs
git submodule add https://github.com/meta-introspector/fs-err.git submodules/submodules/fs-err
git submodule add https://github.com/meta-introspector/either submodules/submodules/either
git submodule add /data/data/com.termux.nix/files/home/rust-bootstrap-nix/ submodules/tools/rust-bootstrap-nix
git submodule add https://github.com/meta-introspector/value-bag submodules/submodules/value-bag
git submodule add https://github.com/meta-introspector/foldhash submodules/submodules/foldhash
git submodule add https://github.com/meta-introspector/write16.git submodules/submodules/write16
git submodule add https://github.com/meta-introspector/constrandom submodules/submodules/constrandom
git submodule add https://github.com/meta-introspector/actix-net submodules/submodules/actix-net
git submodule add https://github.com/meta-introspector/ring.git submodules/submodules/ring
git submodule add https://github.com/meta-introspector/quickcheck.git submodules/submodules/quickcheck
git submodule add https://github.com/meta-introspector/winnow submodules/submodules/winnow
git submodule add https://github.com/meta-introspector/minizinc-introspector.git submodules/minizinc-introspector
git submodule add https://github.com/meta-introspector/serde-ignored.git submodules/submodules/serde-ignored
git submodule add https://github.com/meta-introspector/ron submodules/submodules/ron
git submodule add https://github.com/meta-introspector/wasm_sync submodules/submodules/wasm_sync
git submodule add https://gitlab.com/kornelski/dunce submodules/submodules/dunce
git submodule add https://github.com/meta-introspector/kernel.git submodules/submodules/kernel
git submodule add https://github.com/rusqlite/rusqlite submodules/submodules/rusqlite
git submodule add https://github.com/meta-introspector/ssh2-rs.git submodules/submodules/ssh2-rs
git submodule add https://github.com/meta-introspector/async-std.git submodules/submodules/async-std
git submodule add https://github.com/meta-introspector/tls submodules/submodules/tls
git submodule add https://github.com/RustCrypto/elliptic-curves submodules/submodules/elliptic-curves
git submodule add https://github.com/meta-introspector/is-docker submodules/submodules/is-docker
git submodule add https://github.com/RustCrypto/signatures submodules/submodules/signatures
git submodule add https://github.com/meta-introspector/bumpalo.git submodules/submodules/bumpalo
git submodule add https://github.com/meta-introspector/stability submodules/submodules/stability
git submodule add https://github.com/meta-introspector/embedded-hal submodules/submodules/embedded-hal
git submodule add https://github.com/meta-introspector/fs_extra submodules/submodules/fs_extra
git submodule add https://github.com/meta-introspector/http.git submodules/submodules/http
git submodule add https://github.com/meta-introspector/handlebars-rust submodules/submodules/handlebars-rust
git submodule add https://github.com/meta-introspector/tempfile submodules/submodules/tempfile
git submodule add https://github.com/meta-introspector/tokio-rustls submodules/submodules/tokio-rustls
git submodule add https://github.com/meta-introspector/jwalk.git submodules/submodules/jwalk
git submodule add https://github.com/meta-introspector/semver.git submodules/submodules/semver
git submodule add https://github.com/meta-introspector/litrs.git submodules/submodules/litrs
git submodule add https://github.com/meta-introspector/pin-project submodules/submodules/pin-project
git submodule add https://github.com/meta-introspector/socket2 submodules/submodules/socket2
git submodule add https://github.com/meta-introspector/target-triple.git submodules/submodules/target-triple
git submodule add https://github.com/meta-introspector/zstd-rs submodules/submodules/zstd-rs
git submodule add https://github.com/meta-introspector/aws-lc-rs.git submodules/submodules/aws-lc-rs
git submodule add https://github.com/meta-introspector/thread_local-rs.git submodules/submodules/thread_local-rs
git submodule add https://github.com/meta-introspector/scopeguard.git submodules/submodules/scopeguard
git submodule add https://github.com/meta-introspector/polling submodules/submodules/polling
git submodule add https://github.com/meta-introspector/encoding_rs.git submodules/submodules/encoding_rs
git submodule add https://github.com/meta-introspector/msgpack-rust submodules/submodules/msgpack-rust
git submodule add https://github.com/meta-introspector/document-features submodules/submodules/document-features
git submodule add https://github.com/meta-introspector/utils submodules/submodules/utils
git submodule add https://github.com/meta-introspector/ufmt.git submodules/submodules/ufmt
git submodule add https://github.com/meta-introspector/cfg_aliases.git submodules/submodules/cfg_aliases
git submodule add https://github.com/meta-introspector/filetime.git submodules/submodules/filetime
git submodule add https://github.com/meta-introspector/shell-words submodules/submodules/shell-words
git submodule add https://github.com/meta-introspector/memoffset.git submodules/submodules/memoffset
git submodule add https://github.com/rust-lang/compiler-builtins submodules/submodules/compiler-builtins
git submodule add https://github.com/meta-introspector/rustc-version-rs.git submodules/submodules/rustc-version-rs
git submodule add https://github.com/meta-introspector/globwalk.git submodules/submodules/globwalk
git submodule add https://github.com/Badel2/gg-alloc submodules/submodules/gg-alloc
git submodule add https://github.com/dtolnay/no-panic submodules/submodules/no-panic
git submodule add https://github.com/meta-introspector/unicode-truncate.git submodules/submodules/unicode-truncate
git submodule add https://github.com/meta-introspector/serde-untagged.git submodules/submodules/serde-untagged
git submodule add https://github.com/meta-introspector/is_ci submodules/submodules/is_ci
git submodule add https://github.com/meta-introspector/num-modular.git submodules/submodules/num-modular
git submodule add https://github.com/meta-introspector/paste.git submodules/submodules/paste
git submodule add https://github.com/rust-lang/cargo submodules/submodules/cargo
git submodule add https://github.com/meta-introspector/http-auth submodules/submodules/http-auth
git submodule add https://github.com/meta-introspector/async-attributes.git submodules/submodules/async-attributes
git submodule add https://github.com/meta-introspector/test-strategy submodules/submodules/test-strategy
git submodule add https://github.com/meta-introspector/json5-rs.git submodules/submodules/json5-rs
git submodule add https://github.com/bluss/itertools-num submodules/submodules/itertools-num
git submodule add https://github.com/meta-introspector/try-lock submodules/submodules/try-lock
git submodule add https://github.com/meta-introspector/reqwest submodules/submodules/reqwest
git submodule add https://github.com/meta-introspector/test submodules/submodules/test
git submodule add https://github.com/meta-introspector/parking_lot.git submodules/submodules/parking_lot
git submodule add https://github.com/meta-introspector/inotify-sys.git submodules/submodules/inotify-sys
git submodule add https://github.com/meta-introspector/miniz_oxide.git submodules/submodules/miniz_oxide
git submodule add https://github.com/meta-introspector/float-cmp.git submodules/submodules/float-cmp
git submodule add https://github.com/meta-introspector/libz-sys submodules/submodules/libz-sys
git submodule add https://github.com/meta-introspector/conpty submodules/submodules/conpty
git submodule add https://github.com/meta-introspector/kstring.git submodules/submodules/kstring
git submodule add https://github.com/meta-introspector/git2-rs submodules/submodules/git2-rs
git submodule add https://github.com/meta-introspector/rustls submodules/submodules/rustls
git submodule add https://github.com/meta-introspector/rayon submodules/submodules/rayon
git submodule add https://github.com/meta-introspector/num_threads.git submodules/submodules/num_threads
git submodule add https://github.com/meta-introspector/typeid.git submodules/submodules/typeid
git submodule add https://github.com/diwic/dbus-rs submodules/submodules/dbus-rs
git submodule add https://gitlab.redox-os.org/redox-os/syscall submodules/submodules/syscall
git submodule add https://github.com/meta-introspector/lru-slab submodules/submodules/lru-slab
git submodule add https://github.com/meta-introspector/rust-ed25519-compact.git submodules/submodules/rust-ed25519-compact
git submodule add https://github.com/meta-introspector/rust-errno.git submodules/submodules/rust-errno
git submodule add https://github.com/meta-introspector/windows-rs.git submodules/submodules/windows-rs
git submodule add https://github.com/meta-introspector/glob submodules/submodules/glob
git submodule add https://github.com/meta-introspector/trybuild.git submodules/submodules/trybuild
git submodule add https://github.com/meta-introspector/borsh-rs submodules/submodules/borsh-rs
git submodule add https://github.com/meta-introspector/camino.git submodules/submodules/camino
git submodule add https://github.com/rust-lang/miri submodules/submodules/miri
git submodule add https://github.com/meta-introspector/kvm-sys-rs submodules/submodules/kvm-sys-rs
git submodule add https://github.com/meta-introspector/rustc-hex.git submodules/submodules/rustc-hex
git submodule add https://github.com/meta-introspector/portable-atomic submodules/submodules/portable-atomic
git submodule add https://github.com/meta-introspector/allocator-api2.git submodules/submodules/allocator-api2
git submodule add https://github.com/meta-introspector/annotate-snippets-rs submodules/submodules/annotate-snippets-rs
git submodule add https://github.com/meta-introspector/libtest-mimic submodules/submodules/libtest-mimic
git submodule add https://github.com/meta-introspector/plotters submodules/submodules/plotters
git submodule add https://github.com/meta-introspector/blocking submodules/submodules/blocking
git submodule add https://github.com/meta-introspector/odds submodules/submodules/odds
git submodule add https://gitlab.torproject.org/tpo/core/arti.git submodules/tor-arti
git submodule add https://github.com/meta-introspector/sized-chunks.git submodules/submodules/sized-chunks
git submodule add https://github.com/rust-lang/rust-clippy submodules/submodules/rust-clippy
git submodule add https://github.com/meta-introspector/autocfg.git submodules/submodules/autocfg
git submodule add https://github.com/meta-introspector/crunchy.git submodules/submodules/crunchy
git submodule add https://github.com/meta-introspector/ntapi.git submodules/submodules/ntapi
git submodule add https://github.com/meta-introspector/futures-lite submodules/submodules/futures-lite
git submodule add https://github.com/meta-introspector/typetag.git submodules/submodules/typetag
git submodule add https://github.com/meta-introspector/flate2-rs submodules/submodules/flate2-rs
git submodule add https://github.com/meta-introspector/kv-log-macro submodules/submodules/kv-log-macro
git submodule add https://github.com/meta-introspector/normpath.git submodules/submodules/normpath
git submodule add https://github.com/meta-introspector/serial_test submodules/submodules/serial_test
git submodule add https://github.com/meta-introspector/termtree submodules/submodules/termtree
git submodule add https://github.com/meta-introspector/rust-native-tls submodules/submodules/rust-native-tls
git submodule add https://github.com/meta-introspector/textwrap.git submodules/submodules/textwrap
git submodule add https://github.com/meta-introspector/unicode-width submodules/submodules/unicode-width
git submodule add https://github.com/dtolnay/dissimilar submodules/submodules/dissimilar
git submodule add https://github.com/meta-introspector/mio-aio submodules/submodules/mio-aio
git submodule add https://github.com/meta-introspector/crossbeam.git submodules/submodules/crossbeam
git submodule add https://github.com/meta-introspector/lattice-introspector.git submodules/lattice-introspector
git submodule add https://github.com/meta-introspector/utf8_iter.git submodules/submodules/utf8_iter
git submodule add https://github.com/meta-introspector/zerocopy.git submodules/submodules/zerocopy
git submodule add https://github.com/meta-introspector/syn.git submodules/submodules/syn
git submodule add https://github.com/meta-introspector/jni-sys.git submodules/submodules/jni-sys
git submodule add https://github.com/brendanzab/approx submodules/submodules/approx
git submodule add https://github.com/meta-introspector/objc2.git submodules/submodules/objc2
git submodule add https://github.com/meta-introspector/anes-rs submodules/submodules/anes-rs
git submodule add https://github.com/meta-introspector/atomic-waker submodules/submodules/atomic-waker
git submodule add https://github.com/meta-introspector/rustc-stable-hash submodules/submodules/rustc-stable-hash
git submodule add https://github.com/meta-introspector/pasetors.git submodules/submodules/pasetors
git submodule add https://github.com/meta-introspector/jni-rs.git submodules/submodules/jni-rs
git submodule add https://github.com/Peternator7/strum submodules/submodules/strum
git submodule add https://github.com/rust-lang/rust-analyzer submodules/submodules/rust-analyzer
git submodule add https://github.com/meta-introspector/crc-catalog.git submodules/submodules/crc-catalog
git submodule add https://github.com/meta-introspector/cap.git submodules/submodules/cap
git submodule add https://github.com/meta-introspector/rust-typed-arena submodules/submodules/rust-typed-arena
git submodule add https://github.com/meta-introspector/lazycell.git submodules/submodules/lazycell
git submodule add https://github.com/meta-introspector/subtle.git submodules/submodules/subtle
git submodule add https://github.com/meta-introspector/googletest-rust submodules/submodules/googletest-rust
git submodule add https://github.com/meta-introspector/quick-xml submodules/submodules/quick-xml
git submodule add https://github.com/meta-introspector/maybe-async-rs.git submodules/submodules/maybe-async-rs
git submodule add https://github.com/meta-introspector/notify.git submodules/submodules/notify
git submodule add https://github.com/meta-introspector/env_logger.git submodules/submodules/env_logger
git submodule add https://github.com/meta-introspector/itertools submodules/submodules/itertools
git submodule add https://github.com/meta-introspector/linux-raw-sys submodules/submodules/linux-raw-sys
git submodule add https://github.com/meta-introspector/rust-plist.git submodules/submodules/rust-plist
git submodule add https://github.com/meta-introspector/erased-serde.git submodules/submodules/erased-serde
git submodule add https://github.com/meta-introspector/lazy-static.git submodules/submodules/lazy-static
git submodule add https://github.com/meta-introspector/h2.git submodules/submodules/h2
git submodule add https://github.com/meta-introspector/shell-escape submodules/submodules/shell-escape
git submodule add https://github.com/meta-introspector/gimli.git submodules/submodules/gimli
git submodule add https://github.com/meta-introspector/termcolor.git submodules/submodules/termcolor
git submodule add https://github.com/meta-introspector/memchr.git submodules/submodules/memchr
git submodule add https://github.com/meta-introspector/quote.git submodules/submodules/quote
git submodule add https://github.com/meta-introspector/wit-bindgen.git submodules/submodules/wit-bindgen
git submodule add https://github.com/meta-introspector/num-conv.git submodules/submodules/num-conv
git submodule add https://github.com/meta-introspector/bytes submodules/submodules/bytes
git submodule add https://github.com/sgodwincs/ordered-multimap-rs submodules/submodules/ordered-multimap-rs
git submodule add https://github.com/meta-introspector/opener submodules/submodules/opener
git submodule add https://github.com/meta-introspector/toml submodules/submodules/toml
git submodule add https://github.com/meta-introspector/hyper.git submodules/submodules/hyper
git submodule add https://github.com/meta-introspector/blink-alloc submodules/submodules/blink-alloc
git submodule add https://github.com/BurntSushi/ripgrep submodules/submodules/ripgrep
git submodule add https://github.com/meta-introspector/ipnet.git submodules/submodules/ipnet
git submodule add https://github.com/meta-introspector/ff submodules/submodules/ff
git submodule add https://github.com/NervosFoundation/faster-hex submodules/submodules/faster-hex
git submodule add https://github.com/meta-introspector/rust-pretty-assertions submodules/submodules/rust-pretty-assertions
git submodule add https://github.com/meta-introspector/arraydeque.git submodules/submodules/arraydeque
git submodule add https://github.com/daxpedda/wasm-worker submodules/submodules/wasm-worker
git submodule add https://github.com/meta-introspector/xattr submodules/submodules/xattr
git submodule add https://github.com/meta-introspector/hyper-rustls submodules/submodules/hyper-rustls
git submodule add https://github.com/meta-introspector/warp submodules/submodules/warp
git submodule add https://github.com/meta-introspector/fiat-crypto.git submodules/submodules/fiat-crypto
git submodule add https://huggingface.co/datasets/introspector/rust submodules/datasets/rust
git submodule add https://github.com/meta-introspector/rust-ct-codecs.git submodules/submodules/rust-ct-codecs
git submodule add https://github.com/meta-introspector/unarray.git submodules/submodules/unarray
git submodule add https://github.com/meta-introspector/indexmap.git submodules/submodules/indexmap
git submodule add https://github.com/meta-introspector/compact_str submodules/submodules/compact_str
git submodule add https://github.com/meta-introspector/sharded-slab.git submodules/submodules/sharded-slab
git submodule add https://github.com/meta-introspector/tera.git submodules/submodules/tera
git submodule add https://github.com/dtolnay/serde-stacker submodules/submodules/serde-stacker
git submodule add https://github.com/pyfisch/cbor submodules/submodules/cbor
git submodule add https://github.com/meta-introspector/defer.git submodules/submodules/defer
git submodule add https://github.com/octplane/fsevent-rust submodules/submodules/fsevent-rust
git submodule add https://github.com/meta-introspector/tracing-chrome submodules/submodules/tracing-chrome
git submodule add https://github.com/meta-introspector/convert-case submodules/submodules/convert-case
git submodule add https://github.com/meta-introspector/insta.git submodules/submodules/insta
git submodule add https://github.com/meta-introspector/tiny-keccak.git submodules/submodules/tiny-keccak
git submodule add https://github.com/meta-introspector/pki-types submodules/submodules/pki-types
git submodule add https://github.com/meta-introspector/displaydoc submodules/submodules/displaydoc
git submodule add https://github.com/aitokenteam/ai-agent-terraform.git submodules/ai-agent-terraform
git submodule add https://github.com/meta-introspector/im-rs.git submodules/submodules/im-rs
git submodule add https://github.com/meta-introspector/same-file.git submodules/submodules/same-file
git submodule add https://github.com/meta-introspector/traits submodules/submodules/traits
git submodule add https://github.com/meta-introspector/addr2line.git submodules/submodules/addr2line
git submodule add https://github.com/meta-introspector/generator-rs submodules/submodules/generator-rs
git submodule add https://github.com/meta-introspector/KDFs submodules/submodules/KDFs
git submodule add https://github.com/rust-lang/portable-simd submodules/submodules/portable-simd
git submodule add https://github.com/meta-introspector/os_info submodules/submodules/os_info
git submodule add https://github.com/meta-introspector/once_cell_polyfill submodules/submodules/once_cell_polyfill
git submodule add https://github.com/meta-introspector/relative-path submodules/submodules/relative-path
git submodule add https://github.com/meta-introspector/cpp_demangle submodules/submodules/cpp_demangle
git submodule add https://github.com/meta-introspector/rust-derive-builder.git submodules/submodules/rust-derive-builder
git submodule add https://github.com/meta-introspector/crc-rs.git submodules/submodules/crc-rs
git submodule add https://github.com/meta-introspector/unicode-ident.git submodules/submodules/unicode-ident
git submodule add https://github.com/meta-introspector/tracing-forest submodules/submodules/tracing-forest
git submodule add https://gitlab.com/philbooth/unicode-bom submodules/submodules/unicode-bom
git submodule add https://github.com/meta-introspector/ron-rs submodules/submodules/ron-rs
git submodule add https://github.com/meta-introspector/static-assertions-rs.git submodules/submodules/static-assertions-rs
git submodule add https://github.com/Amanieu/minicov submodules/submodules/minicov
git submodule add https://github.com/meta-introspector/is-terminal submodules/submodules/is-terminal
git submodule add https://github.com/meta-introspector/clang-sys.git submodules/submodules/clang-sys
git submodule add https://github.com/meta-introspector/async-stream submodules/submodules/async-stream
git submodule add https://github.com/meta-introspector/generic-array.git submodules/submodules/generic-array
git submodule add https://github.com/meta-introspector/layout.git submodules/submodules/layout
git submodule add https://github.com/meta-introspector/zip2 submodules/submodules/zip2
git submodule add https://github.com/meta-introspector/parking submodules/submodules/parking
git submodule add https://github.com/meta-introspector/scalable-delayed-dealloc submodules/submodules/scalable-delayed-dealloc
git submodule add https://github.com/meta-introspector/iri-string.git submodules/submodules/iri-string
git submodule add https://github.com/meta-introspector/criterion.rs submodules/submodules/criterion
git submodule add https://github.com/meta-introspector/headers.git submodules/submodules/headers
git submodule add https://github.com/rust-lang/rust/ submodules/submodules/rust
git submodule add https://github.com/meta-introspector/heck submodules/submodules/heck
git submodule add https://github.com/sfackler/rust-jni-sys submodules/submodules/rust-jni-sys
git submodule add https://github.com/meta-introspector/petgraph submodules/submodules/petgraph
git submodule add https://github.com/meta-introspector/twox-hash submodules/submodules/twox-hash
git submodule add https://github.com/meta-introspector/TinyTemplate.git submodules/submodules/TinyTemplate
git submodule add https://github.com/meta-introspector/BLAKE3.git submodules/submodules/BLAKE3
git submodule add https://github.com/meta-introspector/hashes.git submodules/submodules/hashes
git submodule add https://github.com/meta-introspector/orion submodules/submodules/orion
git submodule add https://github.com/meta-introspector/lru-rs.git submodules/submodules/lru-rs
git submodule add https://github.com/ChainSafe/forest.git submodules/filecoin-forest
git submodule add https://github.com/meta-introspector/rust-crc32fast submodules/submodules/rust-crc32fast
git submodule add https://github.com/meta-introspector/typenum submodules/submodules/typenum
git submodule add https://github.com/meta-introspector/normalize-line-endings.git submodules/submodules/normalize-line-endings
git submodule add https://github.com/meta-introspector/num-traits submodules/submodules/num-traits
git submodule add https://github.com/meta-introspector/group submodules/submodules/group
git submodule add https://github.com/meta-introspector/wasi.git submodules/submodules/wasi
git submodule add https://github.com/meta-introspector/unicode-xid submodules/submodules/unicode-xid
git submodule add https://github.com/meta-introspector/time-rs submodules/submodules/time-rs
git submodule add https://github.com/meta-introspector/utf16_iter.git submodules/submodules/utf16_iter
git submodule add https://github.com/meta-introspector/rust-shlex.git submodules/submodules/rust-shlex
git submodule add https://github.com/meta-introspector/vcpkg-rs.git submodules/submodules/vcpkg-rs
git submodule add https://github.com/meta-introspector/anstyle submodules/submodules/anstyle
git submodule add https://github.com/meta-introspector/powerfmt.git submodules/submodules/powerfmt
git submodule add https://github.com/meta-introspector/bstr.git submodules/submodules/bstr
git submodule add https://github.com/meta-introspector/foreign-types submodules/submodules/foreign-types
git submodule add https://github.com/meta-introspector/serde-rs-bytes submodules/submodules/serde-rs-bytes
git submodule add https://github.com/meta-introspector/fallible-streaming-iterator submodules/submodules/fallible-streaming-iterator
git submodule add https://github.com/meta-introspector/mime.git submodules/submodules/mime
git submodule add https://github.com/meta-introspector/openssl-src-rs.git submodules/submodules/openssl-src-rs
git submodule add https://github.com/meta-introspector/console.git submodules/submodules/console
git submodule add https://github.com/meta-introspector/rust-openssl submodules/submodules/rust-openssl
git submodule add https://github.com/meta-introspector/system-configuration-rs.git submodules/submodules/system-configuration-rs
git submodule add https://github.com/meta-introspector/cesu8-rs.git submodules/submodules/cesu8-rs
git submodule add https://github.com/meta-introspector/rust-url submodules/submodules/rust-url
git submodule add https://github.com/meta-introspector/async-net submodules/submodules/async-net
git submodule add https://github.com/meta-introspector/ryu.git submodules/submodules/ryu
git submodule add https://github.com/meta-introspector/rust-hex.git submodules/submodules/rust-hex
git submodule add https://github.com/meta-introspector/clru-rs.git submodules/submodules/clru-rs
git submodule add https://github.com/meta-introspector/async-trait.git submodules/submodules/async-trait
git submodule add https://github.com/meta-introspector/core-foundation-rs submodules/submodules/core-foundation-rs
git submodule add https://github.com/meta-introspector/backtrace-rs submodules/submodules/backtrace-rs
git submodule add https://github.com/meta-introspector/rand submodules/submodules/rand
git submodule add https://github.com/meta-introspector/fastrand submodules/submodules/fastrand
git submodule add https://github.com/meta-introspector/bit-set.git submodules/submodules/bit-set
git submodule add https://github.com/meta-introspector/rustversion.git submodules/submodules/rustversion
git submodule add https://github.com/meta-introspector/arrayref.git submodules/submodules/arrayref
git submodule add https://github.com/meta-introspector/android_system_properties.git submodules/submodules/android_system_properties
git submodule add https://github.com/meta-introspector/rustc-hash submodules/submodules/rustc-hash
git submodule add https://github.com/meta-introspector/supports-hyperlinks submodules/submodules/supports-hyperlinks
git submodule add https://github.com/meta-introspector/time submodules/submodules/time
git submodule add https://github.com/meta-introspector/cryptocorrosion.git submodules/submodules/cryptocorrosion
git submodule add https://github.com/meta-introspector/cast.git submodules/submodules/cast
git submodule add https://github.com/meta-introspector/rust-smallvec submodules/submodules/rust-smallvec
git submodule add https://github.com/meta-introspector/curl-rust.git submodules/submodules/curl-rust
git submodule add https://github.com/meta-introspector/equivalent.git submodules/submodules/equivalent
git submodule add https://github.com/dtolnay/build-alert submodules/submodules/build-alert
git submodule add https://github.com/meta-introspector/async-channel submodules/submodules/async-channel
git submodule add https://github.com/meta-introspector/futures-timer.git submodules/submodules/futures-timer
git submodule add https://github.com/softprops/atty submodules/submodules/atty
git submodule add https://github.com/meta-introspector/ansiterm-rs submodules/submodules/ansiterm-rs
git submodule add https://github.com/meta-introspector/memmap2-rs submodules/submodules/memmap2-rs
git submodule add https://github.com/meta-introspector/tower-http submodules/submodules/tower-http
git submodule add https://github.com/meta-introspector/http-body.git submodules/submodules/http-body
git submodule add https://github.com/meta-introspector/rngs submodules/submodules/rngs
git submodule add https://github.com/meta-introspector/dyn-clone.git submodules/submodules/dyn-clone
git submodule add https://github.com/meta-introspector/partial_ref.git submodules/submodules/partial_ref
git submodule add https://github.com/meta-introspector/async-io submodules/submodules/async-io
git submodule add https://github.com/meta-introspector/serde_urlencoded.git submodules/submodules/serde_urlencoded
git submodule add https://github.com/meta-introspector/webpki submodules/submodules/webpki
git submodule add https://github.com/meta-introspector/num-order.git submodules/submodules/num-order
git submodule add https://github.com/meta-introspector/terminal-size.git submodules/submodules/terminal-size
git submodule add https://github.com/meta-introspector/jobserver-rs submodules/submodules/jobserver-rs
git submodule add https://github.com/meta-introspector/uluru submodules/submodules/uluru
git submodule add https://github.com/meta-introspector/rust-x86 submodules/submodules/rust-x86
git submodule add https://github.com/meta-introspector/libc submodules/submodules/libc
git submodule add https://github.com/dtolnay/indoc submodules/submodules/indoc
git submodule add https://github.com/meta-introspector/temp-env submodules/submodules/temp-env
git submodule add https://github.com/rust-lang/stacker submodules/submodules/stacker
git submodule add https://github.com/meta-introspector/aho-corasick.git submodules/submodules/aho-corasick
git submodule add https://github.com/meta-introspector/findshlibs submodules/submodules/findshlibs
git submodule add https://github.com/meta-introspector/thiserror.git submodules/submodules/thiserror
git submodule add https://github.com/meta-introspector/castaway submodules/submodules/castaway
git submodule add https://github.com/meta-introspector/half-rs submodules/submodules/half-rs
git submodule add https://github.com/meta-introspector/piper submodules/submodules/piper
git submodule add https://github.com/mitsuhiko/sha1-smol submodules/submodules/sha1-smol
git submodule add https://github.com/meta-introspector/ucd-generate.git submodules/submodules/ucd-generate
git submodule add https://github.com/meta-introspector/fxhash submodules/submodules/fxhash
git submodule add https://github.com/meta-introspector/schemars.git submodules/submodules/schemars
git submodule add https://github.com/meta-introspector/wasm-bindgen submodules/submodules/wasm-bindgen
git submodule add https://github.com/rust-analyzer/text-size submodules/submodules/text-size
git submodule add https://github.com/meta-introspector/pulldown-cmark submodules/submodules/pulldown-cmark
git submodule add https://github.com/meta-introspector/quinn submodules/submodules/quinn
git submodule add https://github.com/meta-introspector/os_str_bytes.git submodules/submodules/os_str_bytes
git submodule add https://github.com/pascalkuthe/imara-diff submodules/submodules/imara-diff
git submodule add https://github.com/meta-introspector/dashmap.git submodules/submodules/dashmap
git submodule add https://github.com/meta-introspector/schannel-rs submodules/submodules/schannel-rs
git submodule add https://github.com/meta-introspector/permutohedron.git submodules/submodules/permutohedron
git submodule add https://github.com/meta-introspector/is_executable.git submodules/submodules/is_executable
git submodule add https://github.com/meta-introspector/typesize.git submodules/submodules/typesize
git submodule add https://github.com/meta-introspector/unicode-segmentation submodules/submodules/unicode-segmentation
git submodule add https://github.com/meta-introspector/rust-base64 submodules/submodules/rust-base64
git submodule add https://github.com/meta-introspector/rustls-platform-verifier submodules/submodules/rustls-platform-verifier
git submodule add https://github.com/meta-introspector/leb128.git submodules/submodules/leb128
git submodule add https://github.com/meta-introspector/proc-macro-error-2.git submodules/submodules/proc-macro-error-2
git submodule add https://github.com/meta-introspector/adler2 submodules/submodules/adler2
git submodule add https://github.com/meta-introspector/regex submodules/submodules/regex
git submodule add https://github.com/meta-introspector/tower submodules/submodules/tower
git submodule add https://github.com/meta-introspector/prettyplease.git submodules/submodules/prettyplease
git submodule add https://github.com/meta-introspector/tinyvec.git submodules/submodules/tinyvec
git submodule add https://github.com/meta-introspector/rust_libloading.git submodules/submodules/rust_libloading
git submodule add https://github.com/meta-introspector/libhermit-rs.git submodules/submodules/libhermit-rs
git submodule add https://github.com/meta-introspector/nghttp2-rs.git submodules/submodules/nghttp2-rs
git submodule add https://github.com/meta-introspector/minimal-lexical.git submodules/submodules/minimal-lexical
git submodule add https://github.com/meta-introspector/mime_guess.git submodules/submodules/mime_guess
git submodule add https://github.com/meta-introspector/prodash.git submodules/submodules/prodash
git submodule add https://github.com/meta-introspector/rustls-ffi submodules/submodules/rustls-ffi
git submodule add https://github.com/meta-introspector/miow submodules/submodules/miow
git submodule add https://github.com/meta-introspector/object.git submodules/submodules/object
git submodule add https://github.com/meta-introspector/eigenvalues.git submodules//data/data/com.termux.nix/files/home/experiments/pick-up-nix/vendor/nix/cargo2nix/tools/eigenvalues
git submodule add https://github.com/meta-introspector/macrotest submodules/submodules/macrotest
git submodule add https://github.com/meta-introspector/ciborium.git submodules/submodules/ciborium
git submodule add https://github.com/meta-introspector/bit-vec.git submodules/submodules/bit-vec
git submodule add https://github.com/meta-introspector/getrandom submodules/submodules/getrandom
git submodule add https://github.com/meta-introspector/maplit.git submodules/submodules/maplit
git submodule add https://github.com/meta-introspector/coverage-helper submodules/submodules/coverage-helper
git submodule add https://github.com/sgodwincs/dlv-list-rs submodules/submodules/dlv-list-rs
git submodule add https://github.com/meta-introspector/critical-section submodules/submodules/critical-section
git submodule add https://github.com/meta-introspector/httparse submodules/submodules/httparse
git submodule add https://github.com/meta-introspector/bitmaps.git submodules/submodules/bitmaps
git submodule add https://github.com/meta-introspector/json submodules/submodules/json
git submodule add https://github.com/meta-introspector/fixedbitset submodules/submodules/fixedbitset
git submodule add https://github.com/oli-obk/cargo_metadata submodules/submodules/cargo_metadata
git submodule add https://github.com/meta-introspector/simd-adler32.git submodules/submodules/simd-adler32
git submodule add https://github.com/meta-introspector/instant submodules/submodules/instant
git submodule add https://github.com/vorner/signal-hook submodules/submodules/signal-hook
git submodule add https://github.com/dtolnay/automod submodules/submodules/automod
git submodule add https://github.com/meta-introspector/sval submodules/submodules/sval
git submodule add https://github.com/rust-embedded/heapless submodules/submodules/heapless
git submodule add https://github.com/meta-introspector/want submodules/submodules/want
git submodule add https://github.com/meta-introspector/wait-timeout.git submodules/submodules/wait-timeout
git submodule add https://github.com/meta-introspector/bincode submodules/submodules/bincode
git submodule add https://github.com/meta-introspector/pin-utils submodules/submodules/pin-utils
git submodule add https://github.com/meta-introspector/postcard submodules/submodules/postcard
git submodule add https://github.com/meta-introspector/crossterm.git submodules/submodules/crossterm
git submodule add https://github.com/meta-introspector/structmeta submodules/submodules/structmeta
git submodule add https://github.com/meta-introspector/walkdir.git submodules/submodules/walkdir
git submodule add https://github.com/meta-introspector/scalable-concurrent-containers submodules/submodules/scalable-concurrent-containers
git submodule add https://github.com/meta-introspector/cassowary-rs.git submodules/submodules/cassowary-rs
git submodule add https://github.com/chronotope/humantime submodules/submodules/humantime
git submodule add https://github.com/meta-introspector/rust-fnv submodules/submodules/rust-fnv
git submodule add https://github.com/meta-introspector/async-lock submodules/submodules/async-lock
git submodule add https://github.com/meta-introspector/webpki-roots submodules/submodules/webpki-roots
git submodule add https://github.com/meta-introspector/loom submodules/submodules/loom
git submodule add https://github.com/meta-introspector/jiff.git submodules/submodules/jiff
git submodule add https://github.com/meta-introspector/chrono.git submodules/submodules/chrono
git submodule add https://github.com/meta-introspector/serde submodules/submodules/serde
git submodule add https://github.com/meta-introspector/criterion.rs submodules/submodules/criterion.rs
git submodule add https://github.com/meta-introspector/clap.git submodules/submodules/clap
git submodule add https://github.com/meta-introspector/bitflags.git submodules/submodules/bitflags
git submodule add https://github.com/zonyitoo/rust-ini submodules/submodules/rust-ini
git submodule add https://github.com/meta-introspector/deranged.git submodules/submodules/deranged
git submodule add https://github.com/meta-introspector/hash32.git submodules/submodules/hash32
git submodule add https://github.com/meta-introspector/once_cell.git submodules/submodules/once_cell
git submodule add https://github.com/meta-introspector/oorandom submodules/submodules/oorandom
git submodule add https://github.com/meta-introspector/stable_deref_trait submodules/submodules/stable_deref_trait
git submodule add https://github.com/meta-introspector/constant_time_eq.git submodules/submodules/constant_time_eq
git submodule add https://github.com/meta-introspector/idna_adapter.git submodules/submodules/idna_adapter
git submodule add https://github.com/meta-introspector/content_inspector submodules/submodules/content_inspector
git submodule add https://github.com/GitoxideLabs/gitoxide submodules/submodules/gitoxide
git submodule add https://github.com/meta-introspector/io-uring submodules/submodules/io-uring
git submodule add https://github.com/meta-introspector/arrayvec.git submodules/submodules/arrayvec
git submodule add https://github.com/meta-introspector/crossterm-winapi.git submodules/submodules/crossterm-winapi
git submodule add https://github.com/meta-introspector/proptest submodules/submodules/proptest
git submodule add https://github.com/meta-introspector/ref-cast.git submodules/submodules/ref-cast
git submodule add https://github.com/stainless-steel/md5 submodules/submodules/md5
git submodule add https://github.com/meta-introspector/defmac submodules/submodules/defmac
git submodule add https://github.com/meta-introspector/colorify.git submodules/submodules/colorify
git submodule add https://github.com/meta-introspector/ai-ml-zk-ops.git submodules/ai-ml-zk-ops
git submodule add https://github.com/meta-introspector/futures-concurrency submodules/submodules/futures-concurrency
git submodule add https://github.com/meta-introspector/web-time.git submodules/submodules/web-time
git submodule add https://github.com/tkaitchuck/ahash submodules/submodules/ahash
git submodule add https://github.com/matklad/ungrammar submodules/submodules/ungrammar
git submodule add https://github.com/meta-introspector/yansi submodules/submodules/yansi
git submodule add https://github.com/meta-introspector/encode_unicode submodules/submodules/encode_unicode
git submodule add https://github.com/meta-introspector/inotify.git submodules/submodules/inotify
git submodule add https://github.com/meta-introspector/sync_wrapper.git submodules/submodules/sync_wrapper
git submodule add https://github.com/meta-introspector/untrusted.git submodules/submodules/untrusted
git submodule add https://github.com/meta-introspector/MACs submodules/submodules/MACs
git submodule add https://github.com/meta-introspector/version_check submodules/submodules/version_check
git submodule add https://github.com/meta-introspector/async-executor submodules/submodules/async-executor
git submodule add https://github.com/meta-introspector/pkg-config-rs submodules/submodules/pkg-config-rs
git submodule add https://github.com/meta-introspector/itoa.git submodules/submodules/itoa
git submodule add https://github.com/meta-introspector/rust-cexpr.git submodules/submodules/rust-cexpr
git submodule add https://github.com/meta-introspector/winapi-util.git submodules/submodules/winapi-util
git submodule add https://github.com/meta-introspector/atomic-maybe-uninit submodules/submodules/atomic-maybe-uninit
git submodule add https://github.com/meta-introspector/rust-bindgen submodules/submodules/rust-bindgen
git submodule add https://github.com/meta-introspector/nu-ansi-term.git submodules/submodules/nu-ansi-term
git submodule add https://github.com/meta-introspector/mio submodules/submodules/mio
git submodule add https://github.com/smol-rs/smol submodules/submodules/smol
git submodule add https://github.com/meta-introspector/juniper submodules/submodules/juniper
git submodule add https://github.com/meta-introspector/sysinfo.git submodules/submodules/sysinfo
git submodule add https://github.com/meta-introspector/assert-impl submodules/submodules/assert-impl
git submodule add https://github.com/meta-introspector/xz2-rs.git submodules/submodules/xz2-rs
git submodule add https://github.com/meta-introspector/cmake-rs submodules/submodules/cmake-rs
git submodule add https://codeberg.org/bromind/dot-parser.git submodules/submodules/dot-parser
git submodule add https://github.com/meta-introspector/cfg-if.git submodules/submodules/cfg-if
git submodule add https://github.com/meta-introspector/rand_distr submodules/submodules/rand_distr
git submodule add https://github.com/meta-introspector/crypto-bigint submodules/submodules/crypto-bigint
git submodule add https://github.com/meta-introspector/futures-rs submodules/submodules/futures-rs
git submodule add https://github.com/rust-num/num-complex submodules/submodules/num-complex
git submodule add https://github.com/meta-introspector/defmt.git submodules/submodules/defmt
git submodule add https://github.com/meta-introspector/escargot.git submodules/submodules/escargot
git submodule add https://github.com/meta-introspector/rustls-native-certs submodules/submodules/rustls-native-certs
git submodule add https://github.com/meta-introspector/inventory.git submodules/submodules/inventory
git submodule add https://github.com/meta-introspector/unicode-normalization submodules/submodules/unicode-normalization
git submodule add https://github.com/meta-introspector/quick-error.git submodules/submodules/quick-error
git submodule add https://github.com/meta-introspector/diff.git submodules/submodules/diff
git submodule add https://github.com/smol-rs/async-process submodules/submodules/async-process
git submodule add https://github.com/meta-introspector/winapi-rs submodules/submodules/winapi-rs
git submodule add https://github.com/meta-introspector/icu4x submodules/submodules/icu4x
git submodule add https://github.com/rust-lang/stdarch submodules/submodules/stdarch
git submodule add https://github.com/meta-introspector/wasi-rs.git submodules/submodules/wasi-rs
git submodule add https://github.com/rust-lang/ar_archive_writer submodules/submodules/ar_archive_writer
git submodule add https://gitlab.com/dajoha/color-print submodules/submodules/color-print
git submodule add https://github.com/meta-introspector/expectrl submodules/submodules/expectrl
git submodule add https://github.com/rust-lang/rustfmt submodules/submodules/rustfmt
git submodule add https://github.com/meta-introspector/valuable submodules/submodules/valuable
git submodule add https://github.com/meta-introspector/bytesize.git submodules/submodules/bytesize
git submodule add https://github.com/meta-introspector/combine.git submodules/submodules/combine
git submodule add https://github.com/meta-introspector/hashbrown.git submodules/submodules/hashbrown
git submodule add https://github.com/meta-introspector/mockall submodules/submodules/mockall
git submodule add https://github.com/meta-introspector/actix submodules/submodules/actix
git submodule add https://github.com/meta-introspector/synstructure.git submodules/submodules/synstructure
git submodule add https://github.com/meta-introspector/anyhow.git submodules/submodules/anyhow
git submodule add https://github.com/meta-introspector/rustc-demangle.git submodules/submodules/rustc-demangle
git submodule add https://github.com/meta-introspector/concurrent-queue submodules/submodules/concurrent-queue
git submodule add https://github.com/meta-introspector/iai submodules/submodules/iai
git submodule add https://github.com/meta-introspector/matchers.git submodules/submodules/matchers
