[package]
name = "cargo-repo-sync"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo-repo-sync]
bootstrap_cargo_path = "/nix/store/z32kvhmvy0j5gj4shjvz3qi13a199jlm-rust-minimal-1.92.0-nightly-2025-10-16/bin/cargo"

[dependencies]
cargo-submodule-tool-lib = { path = "../cargo-submodule-tool-lib", features = ["full"] }
clap.workspace = true
clap_derive.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
toml_edit.workspace = true
pathdiff.workspace = true
walkdir.workspace = true
lazy_static.workspace = true

#clap_derive = { version = "4.0.0-rc.1" }
[lints]
workspace = true
