[package]
name = "async-stream"
version = "0.3.5"
edition = "2018"
description = "Asynchronous streams with `yield` syntax"
license = "MIT"
repository = "https://github.com/tokio-rs/async-stream"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
futures-core = { path = "../futures-rs/futures-core" }
futures-sink = { path = "../futures-rs/futures-sink" }
