use std::fs;
use std::path::PathBuf;
use std::collections::{HashMap, VecDeque, HashSet};

use clap::Parser;
use serde::{Deserialize, Serialize};
use petgraph::graph::{DiGraph, NodeIndex};
use petgraph::algo::toposort;

// Re-define CargoEntry and DependencyGraphData to match rust-src-scanner's output
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CargoEntry {
    pub semantic_id: SemanticId,
    pub path: PathBuf,
    pub package_name: String,
    pub package_version: String,
    pub dependencies: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SemanticId {
    pub unique_idx: usize,
    pub weight: f64,
    pub depth: usize,
    pub lmfdb_id: Option<String>,
    pub ast_types_count: u64,
    pub expressions_count: u64,
}

impl std::fmt::Display for SemanticId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ID:{}-W:{:.2}-D:{}-LMFDB:{:?}-Types:{}-Exprs:{}",
               self.unique_idx, self.weight, self.depth, self.lmfdb_id,
               self.ast_types_count, self.expressions_count)
    }
}


#[derive(Debug, Serialize, Deserialize)]
pub struct DependencyGraphData {
    pub nodes: Vec<CargoEntry>,
    pub edges: Vec<(String, String)>, // (source_package_name, target_package_name)
}

#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// Path to the dependency graph JSON file generated by rust-src-scanner
    #[arg(long)]
    graph_input_path: PathBuf,

    /// Optional path to save the layered graph output
    #[arg(long)]
    output_path: Option<PathBuf>,

    /// Optional: Name of the root crate to start layering from (e.g., "rustc-main")
    #[arg(long)]
    root_crate: Option<String>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();

    println!("Reading dependency graph from: {:?}", args.graph_input_path.display());
    let graph_json_content = fs::read_to_string(&args.graph_input_path)?;
    let graph_data: DependencyGraphData = serde_json::from_str(&graph_json_content)?;
    println!("Successfully loaded graph with {} nodes and {} edges.", graph_data.nodes.len(), graph_data.edges.len());

    // Build petgraph from deserialized data
    let mut graph = DiGraph::<String, ()>::new();
    let mut package_name_to_node_index: HashMap<String, NodeIndex> = HashMap::new();

    for node in &graph_data.nodes {
        let node_idx = graph.add_node(node.package_name.clone());
        package_name_to_node_index.insert(node.package_name.clone(), node_idx);
    }

    for (source_name, target_name) in &graph_data.edges {
        if let (Some(&source_idx), Some(&target_idx)) = (package_name_to_node_index.get(source_name), package_name_to_node_index.get(target_name)) {
            graph.add_edge(source_idx, target_idx, ());
        } else {
            // Handle cases where an edge points to a node not in our graph_data.nodes
            // This can happen for external dependencies not fully scanned.
            // For now, we'll just print a warning.
            println!("Warning: Edge from {} to {} involves an unknown node. Skipping.", source_name, target_name);
        }
    }

    // --- NEW Layering Logic (Reverse BFS from leaves) ---
    let mut crate_layers: HashMap<String, usize> = HashMap::new();
    let mut queue: VecDeque<NodeIndex> = VecDeque::new();

    // 1. Identify true leaf nodes (nodes with no outgoing edges) and initialize their layer to 0
    for node_idx in graph.node_indices() {
        if graph.neighbors_directed(node_idx, petgraph::Direction::Outgoing).count() == 0 {
            let crate_name = graph[node_idx].clone();
            crate_layers.insert(crate_name, 0);
            queue.push_back(node_idx);
        }
    }

    // 2. Perform a BFS-like traversal from leaves upwards
    while let Some(current_node_idx) = queue.pop_front() {
        let current_layer = *crate_layers.get(&graph[current_node_idx]).unwrap_or(&0); // Should always be present for nodes in queue

        // Iterate through predecessors (nodes that point to current_node_idx)
        for predecessor_idx in graph.neighbors_directed(current_node_idx, petgraph::Direction::Incoming) {
            let predecessor_name = graph[predecessor_idx].clone();
            let potential_new_layer = current_layer + 1;

            let current_predecessor_layer = *crate_layers.get(&predecessor_name).unwrap_or(&0); // Default to 0 if not yet assigned

            if potential_new_layer > current_predecessor_layer {
                crate_layers.insert(predecessor_name.clone(), potential_new_layer);
                queue.push_back(predecessor_idx); // Add to queue to process its predecessors
            }
        }
    }

    // --- Output Results ---
    println!("\n--- Layered Graph Analysis (Leaves as Layer 0) ---");
    let mut layers_output: HashMap<usize, Vec<String>> = HashMap::new();
    for (crate_name, layer) in &crate_layers {
        layers_output.entry(*layer).or_default().push(crate_name.clone());
    }

    let mut sorted_layers: Vec<(usize, Vec<String>)> = layers_output.into_iter().collect();
    sorted_layers.sort_by_key(|(layer, _)| *layer);

    for (layer, mut crates) in sorted_layers {
        crates.sort(); // Sort crates within each layer alphabetically
        println!("Layer {}:", layer);
        for crate_name in crates {
            println!("  - {}", crate_name);
        }
    }

    // --- Identify Leaf Crates (still useful for verification) ---
    let mut leaf_crates: Vec<String> = Vec::new();
    for node_idx in graph.node_indices() {
        if graph.neighbors_directed(node_idx, petgraph::Direction::Outgoing).count() == 0 {
            leaf_crates.push(graph[node_idx].clone());
        }
    }
    leaf_crates.sort(); // Sort alphabetically for consistent output

    println!("\n--- Original Leaf Crates (Layer 0 in new analysis) ---");
    for leaf in leaf_crates {
        println!("  - {}", leaf);
    }

    // Optional: Save processed data to output_path
    if let Some(output_path) = &args.output_path {
        // For now, just saving the layered structure as JSON
        let output_data = serde_json::to_string_pretty(&crate_layers)?;
        fs::write(output_path, output_data.as_bytes())?;
        println!("\nLayered graph data saved to: {:?}", output_path.display());
    }

    Ok(())
}
