use std::fs;
use std::path::PathBuf;
use std::collections::{HashMap, VecDeque, HashSet};

use clap::Parser;
use serde::{Deserialize, Serialize};
use petgraph::graph::{DiGraph, NodeIndex};
use petgraph::algo::toposort;

// Re-define CargoEntry and DependencyGraphData to match rust-src-scanner's output
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CargoEntry {
    pub semantic_id: SemanticId,
    pub path: PathBuf,
    pub package_name: String,
    pub package_version: String,
    pub dependencies: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SemanticId {
    pub unique_idx: usize,
    pub weight: f64,
    pub depth: usize,
    pub lmfdb_id: Option<String>,
    pub ast_types_count: u64,
    pub expressions_count: u64,
}

impl std::fmt::Display for SemanticId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ID:{}-W:{:.2}-D:{}-LMFDB:{:?}-Types:{}-Exprs:{}",
               self.unique_idx, self.weight, self.depth, self.lmfdb_id,
               self.ast_types_count, self.expressions_count)
    }
}


#[derive(Debug, Serialize, Deserialize)]
pub struct DependencyGraphData {
    pub nodes: Vec<CargoEntry>,
    pub edges: Vec<(String, String)>, // (source_package_name, target_package_name)
}

#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// Path to the dependency graph JSON file generated by rust-src-scanner
    #[arg(long)]
    graph_input_path: PathBuf,

    /// Optional path to save the layered graph output
    #[arg(long)]
    output_path: Option<PathBuf>,

    /// Optional: Name of the root crate to start layering from (e.g., "rustc-main")
    #[arg(long)]
    root_crate: Option<String>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();

    println!("Reading dependency graph from: {:?}", args.graph_input_path.display());
    let graph_json_content = fs::read_to_string(&args.graph_input_path)?;
    let graph_data: DependencyGraphData = serde_json::from_str(&graph_json_content)?;
    println!("Successfully loaded graph with {} nodes and {} edges.", graph_data.nodes.len(), graph_data.edges.len());

    // Build petgraph from deserialized data
    let mut graph = DiGraph::<String, ()>::new();
    let mut package_name_to_node_index: HashMap<String, NodeIndex> = HashMap::new();

    for node in &graph_data.nodes {
        let node_idx = graph.add_node(node.package_name.clone());
        package_name_to_node_index.insert(node.package_name.clone(), node_idx);
    }

    for (source_name, target_name) in &graph_data.edges {
        if let (Some(&source_idx), Some(&target_idx)) = (package_name_to_node_index.get(source_name), package_name_to_node_index.get(target_name)) {
            graph.add_edge(source_idx, target_idx, ());
        } else {
            // Handle cases where an edge points to a node not in our graph_data.nodes
            // This can happen for external dependencies not fully scanned.
            // For now, we'll just print a warning.
            println!("Warning: Edge from {} to {} involves an unknown node. Skipping.", source_name, target_name);
        }
    }

    // --- Layering Logic (BFS) ---
    let mut crate_layers: HashMap<String, usize> = HashMap::new();
    let mut queue: VecDeque<(NodeIndex, usize)> = VecDeque::new();
    let mut visited: HashSet<NodeIndex> = HashSet::new();

    // Determine root nodes (nodes with no incoming edges or specified root_crate)
    let mut root_nodes = Vec::new();
    if let Some(root_crate_name) = &args.root_crate {
        if let Some(&root_idx) = package_name_to_node_index.get(root_crate_name) {
            root_nodes.push(root_idx);
            println!("Starting layering from specified root crate: {}", root_crate_name);
        } else {
            eprintln!("Warning: Specified root crate '{}' not found in graph. Falling back to all nodes with no incoming edges.", root_crate_name);
        }
    }

    if root_nodes.is_empty() {
        for node_idx in graph.node_indices() {
            if graph.neighbors_directed(node_idx, petgraph::Direction::Incoming).count() == 0 {
                root_nodes.push(node_idx);
            }
        }
        println!("Starting layering from {} root nodes (no incoming edges).", root_nodes.len());
    }

    for &root_idx in &root_nodes {
        if visited.insert(root_idx) {
            queue.push_back((root_idx, 0));
            crate_layers.insert(graph[root_idx].clone(), 0);
        }
    }

    while let Some((current_node_idx, current_layer)) = queue.pop_front() {
        for neighbor_idx in graph.neighbors_directed(current_node_idx, petgraph::Direction::Outgoing) {
            if visited.insert(neighbor_idx) {
                let neighbor_name = graph[neighbor_idx].clone();
                let new_layer = current_layer + 1;
                crate_layers.insert(neighbor_name.clone(), new_layer);
                queue.push_back((neighbor_idx, new_layer));
            }
        }
    }

    // --- Identify Leaf Crates ---
    let mut leaf_crates: Vec<String> = Vec::new();
    for node_idx in graph.node_indices() {
        if graph.neighbors_directed(node_idx, petgraph::Direction::Outgoing).count() == 0 {
            leaf_crates.push(graph[node_idx].clone());
        }
    }
    leaf_crates.sort(); // Sort alphabetically for consistent output

    // --- Output Results ---
    println!("\n--- Layered Graph Analysis ---");
    let mut layers_output: HashMap<usize, Vec<String>> = HashMap::new();
    for (crate_name, layer) in &crate_layers {
        layers_output.entry(*layer).or_default().push(crate_name.clone());
    }

    let mut sorted_layers: Vec<(usize, Vec<String>)> = layers_output.into_iter().collect();
    sorted_layers.sort_by_key(|(layer, _)| *layer);

    for (layer, mut crates) in sorted_layers {
        crates.sort(); // Sort crates within each layer alphabetically
        println!("Layer {}:", layer);
        for crate_name in crates {
            println!("  - {}", crate_name);
        }
    }

    println!("\n--- Leaf Crates ---");
    for leaf in leaf_crates {
        println!("  - {}", leaf);
    }

    // Optional: Save processed data to output_path
    if let Some(output_path) = &args.output_path {
        // For now, just saving the layered structure as JSON
        let output_data = serde_json::to_string_pretty(&crate_layers)?;
        fs::write(output_path, output_data.as_bytes())?;
        println!("\nLayered graph data saved to: {:?}", output_path.display());
    }

    Ok(())
}
