[package]
name = "rusttycoon"
categories.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
include.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "rusttycoon" # The name of the executable
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
rocksdb = { workspace = true } # Added rocksdb dependency
chrono = { workspace = true } # Added for timestamps
serde_json = { workspace = true } # Added for parsing flake.lock
quote = { workspace = true } # Added for Rust code generation
serde = { workspace = true, features = ["derive"] } # Added for serialization
typetag = "0.2" # Added for trait object serialization
syntax = { path = "../../submodules/rust-analyzer/crates/syntax" }
base-db = { path = "../../submodules/rust-analyzer/crates/base-db" }
ide-db = { path = "../../submodules/rust-analyzer/crates/ide-db" }
ide-assists = { path = "../../submodules/rust-analyzer/crates/ide-assists" }
rust-mcp-server = { path = "../rust-mcp-server" }
factory_abi = { path = "../factory_abi" }
libloading = "0.7"



[lints]
workspace = true
