[package]
name = "rusttycoon"
categories.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
include.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
rocksdb = { workspace = true } # Added rocksdb dependency
chrono = "0.4" # Added for timestamps
rust-mcp-server = { path = "../rust-mcp-server" }


[lints]
workspace = true
