[package]
name = "rust-mcp-server"
categories.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
include.workspace = true

[dependencies]
lsp-server = "0.7.4" # Or latest compatible version
lsp-types = "0.94.0" # Version compatible with lsp-server
anyhow = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits", "visit"] }
quote = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
libloading = "0.8.3"
mcp-plugin-traits = { path = "../mcp-plugin-traits" }
rocksdb = "0.21.0"
sha2 = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true
