[package]
name = "dep2submodule"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
walkdir.workspace = true
toml_edit.workspace = true
cargo_metadata.workspace = true
clap = { workspace = true, features = ["derive"] }
pathdiff.workspace = true

[lints]
workspace = true
