[package]
name = "bigger-project"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = "0.10"

[dependencies.tokio]
features = ["macros"]
version = "0.2"

[build-dependencies.anyhow]
workspace = true

[build-dependencies.introspector_decl2_macros]
workspace = true

[build-dependencies.proc-macro2]
workspace = true

[build-dependencies.quote]
workspace = true

[build-dependencies.syn]
workspace = true

[patch]
