[package]
name = "trait-fixer-lang-items-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
trait-fixer-lang-items-trait = { path = "../trait-fixer-lang-items-trait" }
trait-fixer-rustc-mock = { path = "../trait-fixer-rustc-mock" }
rustc_hir = { workspace = true }
rustc_span = { workspace = true }
#rustc_hir = { path = "../../../submodules/rust/compiler/rustc_hir" }
