{
  description = "Nix flake for the trait-fixer tool";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    cargo2nix.url = "github:cargo2nix/cargo2nix/release-0.12"; # Pin to a specific release for stability
  };

  outputs = { self, nixpkgs, flake-utils, cargo2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ cargo2nix.overlays.default ]; # Apply cargo2nix overlay
        };
        rustPkgs = pkgs.rustBuilder.makePackageSet {
          packageFun = import ./Cargo.nix; # Generated by cargo2nix
        };
      in {
        packages.default = rustPkgs.workspace.trait-fixer; # Assuming the crate name is "trait-fixer"
        
        devShells.default = pkgs.mkShell {
          inputsFrom = [ self.packages.default ];
          buildInputs = [
            pkgs.rustc # Provide rustc in the devShell
            pkgs.cargo # Provide cargo in the devShell
          ];
          # Make the trait-fixer executable available in the devShell PATH
          shellHook = ''
            export PATH=${rustPkgs.workspace.trait-fixer}/bin:$PATH
          '';
        };
      });
}
