[package]
name = "cargo-repo-sync-cli"
version = "0.1.0"
edition = "2021" # Using 2021 edition for new Rust projects

[dependencies]
clap = { workspace = true }
anyhow.workspace = true
toml_edit.workspace = true
walkdir.workspace = true
url.workspace = true
serde.workspace = true
regex.workspace = true
lazy_static.workspace = true
serde_json.workspace = true
pathdiff.workspace = true
md5.workspace = true
git2.workspace = true
sha1.workspace = true
lru = "0.12"
sha2.workspace = true
hex = "0.4"
cargo_metadata.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "add_submodules"
path = "src/bin/add_submodules.rs"

[package.metadata.repo-manager] # Keeping this for now, will adapt as needed
git_path = "/data/data/com.termux.nix/files/home/.nix-profile/bin/git"
gh_path = "/data/data/com.termux.nix/files/home/.nix-profile/bin/gh"
