[package]
name = "factory_block_factory_block"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rusttycoon = { path = "../rusttycoon" }
monster_math_traits = { path = "../monster_math_traits" }
prelude-generator = { path = "../../tools/rust-bootstrap-nix/prelude-generator" }
split-expanded-lib = { path = "../../tools/rust-bootstrap-nix/split-expanded-lib" }
ast_parser_impl = { path = "../ast_parser_impl" }
