[package]
name = "trait-fixer-compiler-host-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
trait-fixer-compiler-host-trait = { path = "../trait-fixer-compiler-host-trait" }
trait-fixer-rustc-mock = { path = "../trait-fixer-rustc-mock" }
rustc_driver = { workspace = true } # For rustc_driver::Callbacks
