pub mod add_submodules;
pub mod submodule_status;
pub mod generate_nix;
pub mod generate_patches;
pub mod analyze;
pub mod generate_workspaces;
pub mod update_cargo_toml;
pub mod process_tt_txt;
pub mod collect_repo_state;