#![forbid(unsafe_code)]

use std::{
    fs,
    io::{self, BufRead, Read, Write}, // Added Read trait
    path::PathBuf,
};

use anyhow::{Context, Result, anyhow};
use cargo::core::resolver::features::{CliFeatures, HasDevUnits};
use cargo::{
    core::{
        Workspace,
        compiler::{CompileKind, RustcTargetData},
    },
    ops::resolve_with_previous,
    util::important_paths::find_root_manifest_for_wd,
};
use clap::Command;
use clap_complete::{Generator, generate};
use colorify::colorify;
use semver::{Version, VersionReq};
use sha2::{Digest, Sha256};
use tera::Tera;

use crate::template::{BuildPlan, ResolvedPackage};
use crate::traits::CargoResolver;

pub mod discovery; // Add discovery module
pub mod expr;
pub mod file_writer; // Add file_writer module
pub mod generate_cargo_nix;
pub mod manifest;
pub mod platform;
pub mod print_completions; // Add print_completions module
pub mod stdout_writer; // Add stdout_writer module
pub mod template;
pub mod traits;
pub mod version; // Add version module
pub mod version_attributes; // Add version_attributes module
pub mod version_constants; // Add version_constants module
pub mod version_req; // Add version_req module // Add generate_cargo_nix module

pub fn print_completions<G: Generator>(generator: G, cmd: &mut Command) {
    generate(
        generator,
        cmd,
        cmd.get_name().to_string(),
        &mut io::stdout(),
    );
}

pub fn version() -> Version {
    // Since `CARGO_PKG_VERSION` is provided by Cargo itself, which uses the same `semver` crate to
    // parse version strings, the `unwrap()` below should never fail.
    Version::parse(env!("CARGO_PKG_VERSION")).unwrap()
}

pub fn read_version_attribute(path: &PathBuf) -> Result<Version> {
    let file = fs::File::open(path).context(format!("Couldn't open file {}", path.display()))?;
    io::BufReader::new(file)
        .lines()
        .filter_map(|line| line.ok())
        .find(|line| line.trim_start().starts_with(crate::version_constants::VERSION_ATTRIBUTE_NAME))
        .and_then(|s| {
            if let Some(i) = s.find('"') {
                if let Some(j) = s.rfind('"') {
                    return Version::parse(&s[i + 1..j]).ok();
                }
            }
            None
        })
        .ok_or_else(|| {
            anyhow!(
                "Could not find a valid '{}' in '{}'. This might happen if the file is empty or malformed. If you are generating Cargo.nix for the first time, you can safely delete the existing file or use the --overwrite flag.",
                crate::version_constants::VERSION_ATTRIBUTE_NAME,
                path.display()
            )
        })
}

pub fn version_req(path: &PathBuf) -> Result<(VersionReq, Version)> {
    let version = crate::version_attributes::read_version_attribute(path)?;
    let req = format!(">={}.{}", version.major, version.minor);
    VersionReq::parse(&req)
        .context(format!("parse {} found in {}", req, path.display()))
        .map_err(anyhow::Error::from)
        .map(|req| (req, version))
}

pub fn write_to_file(path: &PathBuf, rendered: &str, overwrite: &bool) -> Result<()> {
    if !overwrite && path.exists() {
        let (vers_req, ver) = crate::version_req::version_req(path)?;
        if !vers_req.matches(&crate::version::version()) {
            let mut message = format!(colorify!(red_bold: "Version {} [{}]\n"), vers_req, ver);
            message.push_str(&format!(
                colorify!(red: "Your cargo2nix version is {}, whereas the file '{}' was generated by a newer version of cargo2nix.\n"),
                crate::version::version(),
                path.display()
            ));
            message.push_str(&format!(
                colorify!(red: "Please upgrade your cargo2nix ({}) to proceed."),
                vers_req
            ));
            return Err(anyhow!("{}", message));
        }

        println!(
            colorify!(green_bold: "Version {} matches the requirement {} [{}]"),
            crate::version::version(),
            vers_req,
            ver
        );
        print!(
            "warning: do you want to overwrite '{}'? yes/no: ",
            path.display()
        );

        io::stdout().flush()?;
        let mut line = String::new();
        io::stdin().read_line(&mut line)?;
        if line.trim() != "yes" {
            println!("aborted!");
            return Ok(());
        }
    }

    let mut temp_file = tempfile::Builder::new()
        .tempfile()
        .context("could not create new temporary file")?;

    write!(temp_file, "{}", rendered)?;

    if let Err(err) = temp_file.persist(path) {
        let (_, temp_path) = err.file.keep()?;
        std::fs::copy(temp_path, path)
            .context(format!("could not write file to {}", path.display()))?;
    }

    Ok(())
}

pub fn write_to_stdout(rendered: &str) -> Result<()> {
    write!(io::stdout().lock(), "{}", rendered)?;
    Ok(())
}

pub fn generate_cargo_nix(workspace_directory: &PathBuf, locked: bool) -> Result<String> {
    let config = {
        let mut config = cargo::util::GlobalContext::default()?;
        config.configure(0, false, None, false, locked, false, &None, &[], &[])?;
        config
    };

    let root_manifest_path = find_root_manifest_for_wd(workspace_directory)?;
    let ws = Workspace::new(&root_manifest_path, &config)?;

    if !locked {
        let mut registry = ws.package_registry()?;
        let mut resolve = resolve_with_previous(
            &mut registry,
            &ws,
            &CliFeatures::new_all(true),
            HasDevUnits::Yes,
            None,
            None,
            &[],
            true,
        )?;
        cargo::ops::write_pkg_lockfile(&ws, &mut resolve)?;
    }

    // To get a list of all packages with all features and dependencies that
    // might be enabled present, we first resolve with all features turned on
    let requested_kinds = CompileKind::from_requested_targets(ws.gctx(), &[])?;
    let mut target_data = RustcTargetData::new(&ws, &requested_kinds)?;

    let cargo_resolver = crate::traits::DefaultCargoResolver; // Instantiate the resolver

    // Resolve entire workspace with all features.
    let resolved_all_opts =
        cargo_resolver.resolve_with_all_features(&ws, &mut target_data, &requested_kinds)?;
    let _resolved_all = &resolved_all_opts.targeted_resolve;

    let pkgs_by_id = resolved_all_opts
        .pkg_set
        .get_many(resolved_all_opts.pkg_set.package_ids())?
        .iter()
        .map(|pkg| (pkg.package_id(), *pkg))
        .collect();

    let mut rpkgs_by_id = resolved_all_opts
        .pkg_set
        .get_many(resolved_all_opts.pkg_set.package_ids())?
        .iter()
        .map(|pkg| {
            ResolvedPackage::new(pkg, &pkgs_by_id, &resolved_all_opts.targeted_resolve) // Use resolved_all_opts.targeted_resolve
                .map(|res| (pkg.package_id(), res))
        })
        .collect::<Result<_>>()?;

    // Resolve with just packages but no features turned on.  We can compare
    // with this `Resolve` to detect if turning on a feature made a
    // dependency or feature appear
    let resolved_no_features_opts =
        cargo_resolver.resolve_with_no_features(&ws, &mut target_data, &requested_kinds)?;
    let resolved_no_features = &resolved_no_features_opts.targeted_resolve;

    let root_pkgs: Vec<_> = ws.members().collect();

    // using the resolved_no_features Resolve, if a package or feature is
    // turned on, then it doesn't depend on any top-level features. While it
    // could depend on which workspace package is built, we always have to
    // assume that any workspace package could be built and build at least
    // that much.
    cargo_resolver.mark_required(&resolved_no_features, &mut rpkgs_by_id)?;

    for pkg in root_pkgs.iter() {
        cargo_resolver.mark_feature_activations(
            pkg,
            &ws,
            &resolved_no_features,
            &mut rpkgs_by_id,
            &mut target_data,
            &requested_kinds,
        )?;
    }

    // Certain optionality cases are redundant, such as including an optional
    // dependency always activates its feature.  These cases are reduced to
    // Optionality::Required
    crate::template::simplify_optionality(rpkgs_by_id.values_mut());

    let root_manifest = fs::read_to_string(&root_manifest_path)?;
    let profiles = manifest::extract_profiles(&root_manifest);

    use hex; // Add this import

    // ... (rest of the imports)

    let cargo_lock_path = root_manifest_path.clone().with_file_name("Cargo.lock");
    let mut hasher = Sha256::new();
    let mut file = fs::File::open(&cargo_lock_path).context(format!(
        "Does the Cargo.lock file exist at {}?",
        cargo_lock_path.display()
    ))?;
    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer)?;
    hasher.update(&buffer);
    let cargo_lock_hash: String = hex::encode(hasher.finalize());
    let plan = BuildPlan::from_items(
        cargo_lock_hash,
        root_pkgs,
        profiles,
        rpkgs_by_id,
        workspace_directory,
    )?;
    let mut tera = Tera::default();
    tera.add_raw_template(
        "Cargo.nix.tera",
        include_str!("../../../templates/Cargo.nix.tera"),
    )?;
    let context = tera::Context::from_serialize(plan)?;
    let rendered = tera.render("Cargo.nix.tera", &context)?;

    Ok(rendered)
}
