# #   Unchanged cargo v0.86.0 (available: v0.94.0)
# #   Unchanged cargo-platform v0.2.0 (available: v0.3.1)
# #   Unchanged curl v0.4.48 (available: v0.4.49)
# #   Unchanged generic-array v0.14.7 (available: v0.14.9)
# #   Unchanged git2 v0.19.0 (available: v0.21.0)
# #   Unchanged lru v0.12.5 (available: v0.16.2)
# #   Unchanged md5 v0.7.0 (available: v0.8.0)
# #   Unchanged nix v0.30.0 (available: v0.30.1)
# [patch."https://github.com/meta-introspector/allocator-api2"]
# allocator-api2 = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/allocator-api2" }
# [patch."https://github.com/meta-introspector/rust-base64"]
# base64 = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/rust-base64" }

# [patch."https://github.com/meta-introspector/config-rs"]
# config = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/config-rs" }
# [patch."https://github.com/meta-introspector/dashmap"]
# dashmap = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/dashmap" }
# [patch."https://github.com/meta-introspector/dlv-list-rs"]
# dlv-list = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/dlv-list-rs" }
# [patch."https://github.com/meta-introspector/faster-hex"]
# faster-hex = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/faster-hex" }
# [patch."https://github.com/meta-introspector/hashbrown"]
# hashbrown = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/hashbrown" }
# [patch."https://github.com/meta-introspector/heapless"]
# heapless = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/heapless" }
# [patch."https://github.com/meta-introspector/ordered-multimap-rs"]
# ordered-multimap = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/ordered-multimap-rs" }
# [patch."https://github.com/meta-introspector/ron-rs"]
# ron = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/ron-rs" }
# [patch."https://github.com/meta-introspector/rust-ini"]
# rust-ini = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/rust-ini" }
# [patch."https://github.com/meta-introspector/time-rs"]
# #time = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/time-rs/time" }
# time-core = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/time-rs/time-core" }
# time-macros = { path = "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/cargo2nix/submodules/time-rs/time-macros" }

