#include "../../include/monster_ast.hh"
#include <fstream>
#include <sstream>

namespace MonsterGroup {

class MonsterSaveStream {
private:
    std::ostringstream buffer_;
    std::string filename_;
    
public:
    MonsterSaveStream(const std::string& filename) : filename_(filename) {}
    
    template<typename T>
    MonsterSaveStream& operator<<(const T& value) {
        buffer_ << value;
        return *this;
    }
    
    void save() {
        std::ofstream file(filename_);
        file << buffer_.str();
        file.close();
    }
    
    std::string str() const {
        return buffer_.str();
    }
};

void save_monster_traits(const std::vector<TraitNode>& traits, const std::string& filename) {
    MonsterSaveStream stream(filename);
    
    stream << "# Monster Group Trait Mapping\n";
    stream << "# Generated by Monster Group Cargo2Nix\n\n";
    
    for (const auto& trait : traits) {
        stream << "trait: " << trait.name << "\n";
        stream << "  element: " << trait.monster_element << "\n";
        stream << "  hecke: " << trait.hecke_value << "\n";
        stream << "  hash: " << trait.hash_value << "\n\n";
    }
    
    stream.save();
}

std::string format_monster_solution(const std::vector<uint64_t>& elements) {
    std::ostringstream result;
    
    result << "Monster Group Solution:\n";
    result << "Elements: [";
    for (size_t i = 0; i < elements.size(); i++) {
        if (i > 0) result << ", ";
        result << elements[i];
    }
    result << "]\n";
    
    uint64_t sum = 0;
    for (auto elem : elements) {
        sum += elem;
    }
    result << "Sum: " << sum << "\n";
    result << "Sum mod 24: " << (sum % RAMANUJAN_MOD) << "\n";
    
    return result.str();
}

} // namespace MonsterGroup
