[package]
name = "declaration_aggregator"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
macro_wrapper_lib = { workspace=true }
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
gemini_rustc_data_structures = { workspace = true }
