[package]
name = "cargo-wrapdecls"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-wrapdecls"
path = "src/main.rs"

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
log = { workspace = true }
walkdir = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true, features = ["std"] }
lazy_static = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }