[package]
name = "simple-example"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[build-dependencies.anyhow]
workspace = true

[build-dependencies.introspector_decl2_macros]
workspace = true

[build-dependencies.proc-macro2]
workspace = true

[build-dependencies.quote]
workspace = true

[build-dependencies.syn]
workspace = true

[patch]
