#!/bin/bash

# This script reads a JSON array of repository information (generated by generate_repolist.sh)
# and performs git submodule operations (fork, add, update).
#
# Usage: ./process_repolist.sh <repolist_json_file>
#
# Requires 'jq' for JSON parsing and 'gh' for GitHub CLI operations.

REPOLIST_FILE="$1"

if [ -z "$REPOLIST_FILE" ]; then
    echo "Usage: $0 <repolist_json_file>"
    exit 1
fi

if [ ! -f "$REPOLIST_FILE" ]; then
    echo "Error: Repolist file '$REPOLIST_FILE' not found."
    exit 1
fi

# Check for jq and gh
if ! command -v jq &> /dev/null; then
    echo "Error: 'jq' is not installed. Please install it to run this script."
    exit 1
fi

if ! command -v gh &> /dev/null; then
    echo "Error: 'gh' (GitHub CLI) is not installed. Please install it to run this script."
    exit 1
fi

# Read executable paths from Cargo.toml metadata (similar to repo_manager)
# This part assumes the script is run from the cargo2nix root.
MANIFEST_DIR="$(dirname "$(realpath "$0")")"
CARGO_TOML_PATH="${MANIFEST_DIR}/Cargo.toml"

# Fallback if CARGO_TOML_PATH is not correct for this script's execution context
if [ ! -f "$CARGO_TOML_PATH" ]; then
    CARGO_TOML_PATH="./Cargo.toml" # Assume current dir if not found in script's dir
fi

GIT_EXECUTABLE_PATH=$(grep -A 5 '\[package.metadata.repo-manager\]' "$CARGO_TOML_PATH" | grep 'git_path' | sed -E 's/.*=\s*"(.*)"/\1/')
GH_EXECUTABLE_PATH=$(grep -A 5 '\[package.metadata.repo-manager\]' "$CARGO_TOML_PATH" | grep 'gh_path' | sed -E 's/.*=\s*"(.*)"/\1/')

if [ -z "$GIT_EXECUTABLE_PATH" ]; then
    echo "Warning: 'git_path' not found in Cargo.toml metadata. Using default 'git'."
    GIT_EXECUTABLE_PATH="git"
fi
if [ -z "$GH_EXECUTABLE_PATH" ]; then
    echo "Warning: 'gh_path' not found in Cargo.toml metadata. Using default 'gh'."
    GH_EXECUTABLE_PATH="gh"
fi

# Ensure submodules directory exists
mkdir -p submodules


ensure_fork_and_branch() {
    local owner="$1"
    local repo_name="$2"
    local target_org="$3"
    local target_branch="$4"
    local fork_url="https://github.com/${target_org}/${repo_name}"

    # 1. Ensure the fork exists on GitHub
    if ! "$GH_EXECUTABLE_PATH" repo view "${target_org}/${repo_name}" &> /dev/null; then
        echo "  - Forking ${owner}/${repo_name} to ${target_org}..."
        if ! "$GH_EXECUTABLE_PATH" repo fork "${owner}/${repo_name}" --org "${target_org}" --remote --fork-name "${repo_name}"; then
            echo "Error forking ${owner}/${repo_name}. This might be due to rate limiting or the upstream repository not existing. Skipping submodule add/update for this repo." >&2
            return 1
        fi
        sleep 5 # Wait to avoid GitHub API rate limiting
    else
        echo "  - Fork ${target_org}/${repo_name} already exists on GitHub."
    fi

    # 2. Ensure the target branch exists on the fork and is up-to-date
    # This part will be handled within the submodule directory after cloning/updating
    return 0
}

# Read the JSON array
jq -c 'reverse | .[]' "$REPOLIST_FILE" | while read -r repo_json; do
    REPO_URL=$(echo "$repo_json" | jq -r '.repo_url')
    OWNER=$(echo "$repo_json" | jq -r '.owner')
    REPO_NAME=$(echo "$repo_json" | jq -r '.repo_name')
    TARGET_ORG=$(echo "$repo_json" | jq -r '.target_org')
    TARGET_BRANCH=$(echo "$repo_json" | jq -r '.target_branch')
    SUBMODULE_PATH="submodules/${REPO_NAME}"
    FORK_URL="https://github.com/${TARGET_ORG}/${REPO_NAME}"

    SUBMODULE_PATH="submodules/${REPO_NAME}"
    mkdir -p "$SUBMODULE_PATH" # Ensure submodule directory exists for logs

    TEMP_LOG_FILE="${SUBMODULE_PATH}/process-repo.tmp"
    LOG_FILE="${SUBMODULE_PATH}/process-repo.log"
    ERR_FILE="${SUBMODULE_PATH}/process-repo.err"

    # Clear previous logs for this run
    rm -f "$LOG_FILE" "$ERR_FILE" "$TEMP_LOG_FILE"

    echo "--- Processing ${REPO_NAME} ---"

    # Execute the entire block for this repo, redirecting all output to a temporary file
    (
        echo "--- Starting processing for ${REPO_NAME} ---"

        if ! ensure_fork_and_branch "$OWNER" "$REPO_NAME" "$TARGET_ORG" "$TARGET_BRANCH"; then
            echo "Failed to ensure fork and branch for ${REPO_NAME}. Skipping."
            exit 1 # Indicate failure
        fi

        if [ -d "$SUBMODULE_PATH" ]; then
            echo "Submodule ${REPO_NAME} already exists. Updating."
            (
                cd "$SUBMODULE_PATH" || exit 1
                echo "  - Ensuring remotes are set..."
                if ! "$GIT_EXECUTABLE_PATH" remote get-url upstream &> /dev/null; then
                    echo "    - Adding upstream remote: ${REPO_URL}"
                    "$GIT_EXECUTABLE_PATH" remote add upstream "$REPO_URL"
                else
                    "$GIT_EXECUTABLE_PATH" remote set-url upstream "$REPO_URL"
                fi

                if ! "$GIT_EXECUTABLE_PATH" remote get-url origin &> /dev/null; then
                    echo "    - Adding origin remote: ${FORK_URL}"
                    "$GIT_EXECUTABLE_PATH" remote add origin "$FORK_URL"
                else
                    "$GIT_EXECUTABLE_PATH" remote set-url origin "$FORK_URL"
                fi

                echo "  - Fetching from remotes..."
                "$GIT_EXECUTABLE_PATH" fetch upstream
                "$GIT_EXECUTABLE_PATH" fetch origin

                echo "  - Checking out/creating branch ${TARGET_BRANCH}..."
                "$GIT_EXECUTABLE_PATH" checkout "$TARGET_BRANCH" || "$GIT_EXECUTABLE_PATH" checkout -b "$TARGET_BRANCH"

                echo "  - Updating local branch from origin/${TARGET_BRANCH}..."
                "$GIT_EXECUTABLE_PATH" checkout "$TARGET_BRANCH" || "$GIT_EXECUTABLE_PATH" checkout -b "$TARGET_BRANCH" "origin/${TARGET_BRANCH}"
                "$GIT_EXECUTABLE_PATH" pull --ff-only origin "$TARGET_BRANCH"
                if [ $? -ne 0 ]; then
                    echo "    - Warning: Failed to fast-forward pull. There might be local changes or divergent history. Please resolve manually."
                fi
            ) || exit 1 # Exit subshell if cd or any command inside fails
        else
            echo "Submodule ${REPO_NAME} does not exist. Adding."

            echo "  - Adding submodule ${REPO_NAME}..."
            "$GIT_EXECUTABLE_PATH" submodule add "$REPO_URL" "$SUBMODULE_PATH"
            if [ $? -ne 0 ]; then
                echo "Error adding submodule ${REPO_NAME}. Skipping remote setup."
                exit 1 # Indicate failure
            fi

            (
                cd "$SUBMODULE_PATH" || exit 1
                echo "  - Setting up remotes and branch in new submodule..."
                "$GIT_EXECUTABLE_PATH" remote rename origin upstream
                "$GIT_EXECUTABLE_PATH" remote add origin "$FORK_URL"
                "$GIT_EXECUTABLE_PATH" checkout -b "$TARGET_BRANCH" || "$GIT_EXECUTABLE_PATH" checkout "$TARGET_BRANCH"
                "$GIT_EXECUTABLE_PATH" push -u origin "$TARGET_BRANCH" # Push the new branch to the fork
            ) || exit 1 # Exit subshell if cd or any command inside fails
        fi
        echo "--- Finished processing for ${REPO_NAME} ---"
    ) > "$TEMP_LOG_FILE" 2>&1 # Redirect all stdout and stderr to TEMP_LOG_FILE

    # Check the exit status of the subshell
    if [ $? -ne 0 ]; then
        echo "--- Processing of ${REPO_NAME} FAILED. See ${ERR_FILE} ---"
        mv "$TEMP_LOG_FILE" "$ERR_FILE"
    else
        echo "--- Processing of ${REPO_NAME} SUCCEEDED. See ${LOG_FILE} ---"
        mv "$TEMP_LOG_FILE" "$LOG_FILE"
    fi
    echo "" # Newline for readability
done