[package]
name = "tool-refactorings"
categories.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
include.workspace = true

[dependencies]
gemini_utils = { path = "../../minizinc-introspector/crates/gemini_utils" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tempfile = "3"

[lints]
workspace = true
