[package]
name = "trait-fixer-core-real"
version = "0.1.0"
edition = "2021"

[dependencies]
trait-fixer-core-trait = { path = "../trait-fixer-core-trait" }
trait-fixer-rules-real = { path = "../trait-fixer-rules-real" } # Still needed for rules::Config
rustc_middle = { workspace = true } # Keep for TyCtxt in struct
rustc_hir = { workspace = true }
trait-fixer-rules-trait = { path = "../trait-fixer-rules-trait" }
trait-fixer-attribute-reader-trait = { path = "../trait-fixer-attribute-reader-trait" }
trait-fixer-lang-items-trait = { path = "../trait-fixer-lang-items-trait" }
trait-fixer-trait-checker-trait = { path = "../trait-fixer-trait-checker-trait" }
trait-fixer-hir-info-trait = { path = "../trait-fixer-hir-info-trait" }
trait-fixer-hir-info-real = { path = "../trait-fixer-hir-info-real" }
